version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: tosom_dev_db
    restart: always
    environment:
      POSTGRES_USER: tosom
      POSTGRES_PASSWORD: tosom
      POSTGRES_DB: tosom_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
