const fs = require('fs');
const L = [];
function p(s) { L.push(s); }
p('generator client {');
p('  provider = "prisma-client-js"');
p('}');
p('');
p('datasource db {');
p('  provider = "sqlite"');
p('  url      = env("DATABASE_URL")');
p('}');
p('');
// User Model
p('model User {');
p('  id               String           @id @default(cuid())');
p('  email            String           @unique');
p('  password         String?');
p('  phone            String?');
p('  phoneVerified    Boolean          @default(false)');
p('  onboardingStep   Int              @default(1)');
p('  onboardingComplete Boolean        @default(false)');
p('  deepProfileComplete Boolean        @default(false)');
p('  role             String           @default("USER")');
p('  verified         Boolean           @default(false)');
p('  bannedAt         DateTime?');
p('  deletedAt        DateTime?');
p('  createdAt        DateTime         @default(now())');
p('  updatedAt        DateTime         @updatedAt');
p('  lastMatchAt      DateTime?');
p('  lockedUntil      DateTime?');
p('  profile          Profile?                       @relation("UserProfile")');
p('  conversationsA   Conversation[]                 @relation("ConversationToUserA")');
p('  conversationsB   Conversation[]                 @relation("ConversationToUserB")');
p('  messages         Message[]');
p('  matchesA         Match[]                        @relation("UserAMatches")');
p('  matchesB         Match[]                        @relation("UserBMatches")');
p('  journey          JourneyProgress?               @relation("UserJourney")');
p('  notifications    Notification[]');
p('  resetTokens      PasswordResetToken[]');
p('  twoFactor        TwoFactorSecret?');
p('  auditLogs        AuditLog[]                     @relation("AdminAuditLogs")');
p('  matchQueues      MatchQueue[]');
p('  matchFeedbacks   MatchFeedback[]');
p('  accounts         Account[]');
p('  sessions         Session[]');
p('  @@index([role])');
p('  @@index([email])');
p('  @@index([lastMatchAt])');
p('  @@index([lockedUntil])');
p('}');
p('');
// Profile Model
p('model Profile {');
p('  id                  String   @id @default(cuid())');
p('  userId              String   @unique');
p('  firstName           String?');
p('  lastName            String?');
p('  age                 Int?');
p('  identityName        String?');
p('  lifeSituation       String?');
p('  lifestyle           String?');
p('  personality         String?');
p('  relationshipStyle   String?');
p('  communication       String?');
p('  intimacy            String?');
p('  futureVision        String?');
p('  boundaries          String?');
p('  emotionalNeeds      String?');
p('  lifeRhythm          String?');
p('  maturityLevel       Int?');
p('  securityLevel       String?');
p('  photoUrl            String?');
p('  bio                 String?');
p('  interests           String?');
p('  deepProfileStep     String   @default("IDENTITY")');
p('  deepProfileData     String?');
p('  preferences         String?');
p('  matchTags           String?');
p('  createdAt           DateTime @default(now())');
p('  updatedAt           DateTime @updatedAt');
p('  user                User     @relation("UserProfile", fields: [userId], references: [id])');
p('  @@index([userId])');
p('  @@index([deepProfileStep])');
p('  @@index([matchTags])');
p('}');
p('');
// Match Model
p('model Match {');
p('  id                  String   @id @default(cuid())');
p('  userAId             String');
p('  userBId             String');
p('  status              String   @default("active")');
p('  score               Int      @default(0)');
p('  normalizedScore     Float');
p('  resonanceLevel      String');
p('  explanation         String?');
p('  scoringBreakdown    String?');
p('  matchType           String   @default("resonance")');
p('  matchedAt           DateTime @default(now())');
p('  startedAt           DateTime?');
p('  createdAt           DateTime @default(now())');
p('  updatedAt           DateTime @updatedAt');
p('  userA               User     @relation("UserAMatches", fields: [userAId], references: [id])');
p('  userB               User     @relation("UserBMatches", fields: [userBId], references: [id])');
p('  messages            Message[]');
p('  insights            MatchInsight?');
p('  feedback            MatchFeedback?');
p('  @@unique([userAId, userBId])');
p('  @@index([status])');
p('  @@index([resonanceLevel])');
p('  @@index([score])');
p('}');
p('');
// Message Model
p('model Message {');
p('  id                 String   @id @default(cuid())');
p('  conversationId     String');
p('  senderId           String');
p('  content            String');
p('  type               String   @default("user")');
p('  state              String   @default("SENT")');
p('  createdAt          DateTime @default(now())');
p('  updatedAt          DateTime @updatedAt');
p('  conversation       Conversation @relation(fields: [conversationId], references: [id])');
p('  @@index([conversationId])');
p('  @@index([senderId])');
p('  @@index([createdAt])');
p('}');
p('');
// Conversation Model
p('model Conversation {');
p('  id                 String   @id @default(cuid())');
p('  matchId            String   @unique');
p('  userAId            String');
p('  userBId            String');
p('  createdAt          DateTime @default(now())');
p('  updatedAt          DateTime @updatedAt');
p('  lastMessageAt      DateTime?');
p('  typingStatusA      Boolean  @default(false)');
p('  typingStatusB      Boolean  @default(false)');
p('  chatUntil          DateTime?');
p('  match              Match    @relation(fields: [matchId], references: [id])');
p('  userA              User     @relation("ConversationToUserA", fields: [userAId], references: [id])');
p('  userB              User     @relation("ConversationToUserB", fields: [userBId], references: [id])');
p('  messages           Message[]');
p('  @@index([userAId])');
p('  @@index([userBId])');
p('  @@index([matchId])');
p('}');
p('');
// JourneyProgress Model
p('model JourneyProgress {');
p('  id                 String   @id @default(cuid())');
p('  userId             String   @unique');
p('  user               User     @relation("UserJourney", fields: [userId], references: [id])');
p('  phase              String   @default("EARLY")');
p('  day                Int      @default(1)');
p('  state              String   @default("IN_PROGRESS")');
p('  totalPoints        Int      @default(0)');
p('  resonances         String   @default("[]")');
p('  tasksCompleted     Int      @default(0)');
p('  createdAt          DateTime @default(now())');
p('  updatedAt          DateTime @updatedAt');
p('  @@index([phase])');
p('  @@index([state])');
p('}');
p('');
// Task Model
p('model Task {');
p('  id                 String   @id @default(cuid())');
p('  journeyId          String');
p('  title              String');
p('  description        String?');
p('  phase              String');
p('  day                Int');
p('  completed          Boolean  @default(false)');
p('  completedAt        DateTime?');
p('  createdAt          DateTime @default(now())');
p('  @@index([journeyId])');
p('  @@index([phase])');
p('  @@index([day])');
p('}');
p('');
// TwoFactorSecret Model
p('model TwoFactorSecret {');
p('  id                 String   @id @default(cuid())');
p('  userId             String   @unique');
p('  secret             String');
p('  recoveryCodes      String?');
p('  backupCodes        String?');
p('  createdAt          DateTime @default(now())');
p('  user               User     @relation(fields: [userId], references: [id], onDelete: Cascade)');
p('  @@index([userId])');
p('}');
p('');
// PasswordResetToken Model
p('model PasswordResetToken {');
p('  id                 String   @id @default(cuid())');
p('  userId             String');
p('  token              String   @unique');
p('  expiresOn          DateTime');
p('  createdAt          DateTime @default(now())');
p('  @@index([userId])');
p('  @@index([expiresOn])');
p('}');
p('');
// Notification Model
p('model Notification {');
p('  id                 String   @id @default(cuid())');
p('  userId             String');
p('  type               String');
p('  title              String');
p('  message            String');
p('  read               Boolean  @default(false)');
p('  metadata           String?');
p('  createdAt          DateTime @default(now())');
p('  user               User     @relation(fields: [userId], references: [id], onDelete: Cascade)');
p('  @@index([userId])');
p('  @@index([type])');
p('  @@index([read])');
p('  @@index([createdAt])');
p('}');
p('');
// MatchQueue Model
p('model MatchQueue {');
p('  id                 String   @id @default(cuid())');
p('  userId             String');
p('  status             String   @default("PENDING")');
p('  candidateId        String?');
p('  score              Int?');
p('  createdAt          DateTime @default(now())');
p('  updatedAt          DateTime @updatedAt');
p('  expiresAt          DateTime?');
p('  user               User     @relation(fields: [userId], references: [id], onDelete: Cascade)');
p('  @@index([userId])');
p('  @@index([status])');
p('  @@index([createdAt])');
p('}');
p('');
// MatchFeedback Model
p('model MatchFeedback {');
p('  id                 String   @id @default(cuid())');
p('  matchId            String   @unique');
p('  rating             Int?');
p('  comment            String?');
p('  createdAt          DateTime @default(now())');
p('  match              Match    @relation(fields: [matchId], references: [id])');
p('  @@index([matchId])');
p('}');
p('');
// AuditLog Model
p('model AuditLog {');
p('  id                 String   @id @default(cuid())');
p('  adminId            String');
p('  action             String');
p('  metadata           String?');
p('  createdAt          DateTime @default(now())');
p('  admin              User     @relation("AdminAuditLogs", fields: [adminId], references: [id])');
p('  @@index([adminId])');
p('  @@index([action])');
p('  @@index([createdAt])');
p('}');
p('');
// SystemLog Model
p('model SystemLog {');
p('  id                 String   @id @default(cuid())');
p('  level              String');
p('  message            String');
p('  module             String?');
p('  metadata           String?');
p('  createdAt          DateTime @default(now())');
p('  @@index([level])');
p('  @@index([module])');
p('  @@index([createdAt])');
p('}');
p('');

// PerformanceMetric Model
p('model PerformanceMetric {');
p('  id                 String   @id @default(cuid())');
p('  route              String');
p('  metric             String');
p('  valueMs            Int');
p('  createdAt          DateTime @default(now())');
p('  @@index([route])');
p('  @@index([metric])');
p('  @@index([createdAt])');
p('}');
p('');

// Account Model (NextAuth)
p('model Account {');
p('  id                 String  @id @default(cuid())');
p('  userId             String');
p('  type               String');
p('  provider           String');
p('  providerAccountId  String');
p('  refresh_token      String?');
p('  access_token       String?');
p('  expires_at         Int?');
p('  token_type         String?');
p('  scope              String?');
p('  id_token           String?');
p('  session_state      String?');
p('  user               User    @relation(fields: [userId], references: [id], onDelete: Cascade)');
p('  @@unique([provider, providerAccountId])');
p('  @@index([userId])');
p('}');
p('');

// Session Model (NextAuth)
p('model Session {');
p('  id                 String   @id @default(cuid())');
p('  userId             String');
p('  sessionToken       String   @unique');
p('  expires            DateTime');
p('  user               User     @relation(fields: [userId], references: [id], onDelete: Cascade)');
p('}');
p('');

// VerificationToken Model (NextAuth)
p('model VerificationToken {');
p('  identifier         String');
p('  token              String   @unique');
p('  expires            DateTime');
p('  @@unique([identifier, token])');
p('}');
p('');

// MatchInsight Model
p('model MatchInsight {');
p('  id                 String   @id @default(cuid())');
p('  matchId            String   @unique');
p('  summary            String');
p('  strengths          String');
p('  clarity            String');
p('  starter            String');
p('  model              String?');
p('  tokensOut          Int      @default(0)');
p('  createdAt          DateTime @default(now())');
p('  updatedAt          DateTime @updatedAt');
p('  match              Match    @relation(fields: [matchId], references: [id])');
p('  @@index([matchId])');
p('  @@index([createdAt])');
p('}');
p('');

// RateLimitLog Model
p('model RateLimitLog {');
p('  id                 String   @id @default(cuid())');
p('  userId             String?');
p('  route              String');
p('  createdAt          DateTime @default(now())');
p('  @@index([userId])');
p('  @@index([route])');
p('  @@index([createdAt])');
p('}');
p('');

// MatchingAIRequestLog Model
p('model MatchingAIRequestLog {');
p('  id                 String   @id @default(cuid())');
p('  userId             String');
p('  feature            String');
p('  model              String');
p('  tokensIn           Int');
p('  tokensOut          Int');
p('  latencyMs          Int');
p('  success            Boolean');
p('  traceId            String?');
p('  createdAt          DateTime @default(now())');
p('  @@index([userId])');
p('  @@index([feature])');
p('  @@index([createdAt])');
p('}');
p('');

// Write the file
fs.writeFileSync('/home/george/tosom/prisma/schema.prisma', L.join('\n') + '\n');
console.log('Schema written successfully');
console.log('Lines:', L.length);
