/**
 * Seed: 30-dagers reise-innhald
 * Core-definition: Guidet 30-dagers reise med dagleg refleksjon, tema, oppgåver, resonans
 */

import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

const journeyContent = [
  // ===== FASE 1: Introduksjon (Dag 1-5) =====
  {
    day: 1,
    theme: "Velkomen",
    phase: "EARLY",
    reflectionQuestion: "Kva førte deg hit — til dette rommet, til denne reisen?",
    conversationPrompt: "Fortel kort om kven du er — det som gjer deg til deg.",
    task: null,
    resonanceGoal: "åpne deg",
    systemMessage: "Dere to er her saman. Ta det i dykkar eige tempo. Eit enkelt 'hei' er alltid ein fin start.",
  },
  {
    day: 2,
    theme: "Kvardag",
    phase: "EARLY",
    reflectionQuestion: "Korleis ser ein vanleg dag din ut?",
    conversationPrompt: "Kva er viktigast for deg i kvardagen din?",
    task: "Del ein vanleg dag — kva skjer, kva kjensler er der?",
    resonanceGoal: "trygghet",
    systemMessage: "Kvardagen er der ekte liv skjer. Å dele den er eit teikn på tillit.",
  },
  {
    day: 3,
    theme: "Kjerner",
    phase: "EARLY",
    reflectionQuestion: "Kva er dei tre verdiane du aldri kan leve utan?",
    conversationPrompt: "Kva verdiar driv deg — sjølv når det er tungt?",
    task: "Nemn tre kjerneverdar og kvifor dei betyr noko for deg.",
    resonanceGoal: "verdier-kompatibilitet",
    systemMessage: "Kjerner er grunnsteinen. Å kjenne dei sine eigne, og dela dei, er djupt.",
  },
  {
    day: 4,
    theme: "Sjølvmønster",
    phase: "EARLY",
    reflectionQuestion: "Kva seier om deg at du er du — uavhengig av andre?",
    conversationPrompt: "Kva er noko om deg som få folk merker?",
    task: "Beskriv deg sjølv som du aldri gjer på eit første møte.",
    resonanceGoal: "personleg djupde",
    systemMessage: "Å sjå seg sjølv er ein gave. Å dele det syn med nokon annan er enno djupare.",
  },
  {
    day: 5,
    theme: "Åpning",
    phase: "EARLY",
    reflectionQuestion: "Kva er noko du sjeldan deler med folk du ikkje kjem heilt nær?",
    conversationPrompt: "Er det noko du aldri har fortalt nokon om deg sjølv?",
    task: "Del noko lite, men verkeleg — det treng ikkje vera stort, berre sant.",
    resonanceGoal: "sårbarhet",
    systemMessage: "Dagen er 5. Dere har vore trygge saman. No er det tid for ei mild åpning.",
  },

  // ===== FASE 2: Trygghet (Dag 6-14) =====
  {
    day: 6,
    theme: "Trygghet",
    phase: "BUILDING_TRUST",
    reflectionQuestion: "Kva gjer at du kjener deg trygg med nokon?",
    conversationPrompt: "Kva treng du for å kjenne at dette rommet er trygt?",
    task: "Fortel om noko du treng for å føle deg trygg i ein samtale.",
    resonanceGoal: "trygghets-sjekk",
    systemMessage: "Trygghet kjem ikkje av seg sjølv. Det byggest — ord for ord, dag for dag.",
  },
  {
    day: 7,
    theme: "Grense",
    phase: "BUILDING_TRUST",
    reflectionQuestion: "Kva er grenserne dine — kva du aldri vil gå over?",
    conversationPrompt: "Kva er noko du aldri vil at ei samtale skal gjera?",
    task: "Set ei grense og forklar kvifor — det er ei gave til seg sjølv og til den andre.",
    resonanceGoal: "grense-respekt",
    systemMessage: "Grenser er ikkje veggar — dei er vevar som fortel kvar ein sluttar og den andre byrjar.",
  },
  {
    day: 8,
    theme: "Rom",
    phase: "BUILDING_TRUST",
    reflectionQuestion: "Treng du rom — eller nærleik når ting kjem tungt?",
    conversationPrompt: "Kva foretrekkjer du når noko kjem tungt?",
    task: "Fortel om kva du treng — rom eller nærleik — og kvifor.",
    resonanceGoal: "behov-erkjenning",
    systemMessage: "Å vite kva ein treng er halvparten av å få det. Del det med nokon som lyttar.",
  },
  {
    day: 9,
    theme: "Forventing",
    phase: "BUILDING_TRUST",
    reflectionQuestion: "Kva forventar du av denne reisen — og av deg sjølv?",
    conversationPrompt: "Kva ønskjer du at dette rommet kan bli for deg?",
    task: "Nemn éitt ønskje for denne reisen — det treng ikkje vera stort, berre ærleg.",
    resonanceGoal: "forventning-kompatibilitet",
    systemMessage: "Forventningar er kompass. Dei viser kvar hjartet ditt beveger seg.",
  },
  {
    day: 10,
    theme: "Mote",
    phase: "BUILDING_TRUST",
    reflectionQuestion: "Korlei møter du nokon for fyrste gong — i ord, i tonen, i stillheten?",
    conversationPrompt: "Beskriv det fyrste inntrykket du gir.",
    task: "Fortel om fyrsteinntrykk — kva du gir og kva du tek imot.",
    resonanceGoal: "møte-resonans",
    systemMessage: "Det fyrste inntrykket er som eit vindu. Det fortel kva som ligg bak.",
  },
  {
    day: 11,
    theme: "Tillit",
    phase: "BUILDING_TRUST",
    reflectionQuestion: "Kva er det som gjer tillit lett — eller tungt, for deg?",
    conversationPrompt: "Fortel om noko som gjer tillit lettare for deg.",
    task: "Del ein erfaring med tillit — noko lett eller tungt — det gjer ingenting.",
    resonanceGoal: "tillits-bygg",
    systemMessage: "Tillit er ikkje eit krav — det er eit svar på korleis nokon har møtt deg.",
  },
  {
    day: 12,
    theme: "Refleksjon",
    phase: "BUILDING_TRUST",
    reflectionQuestion: "Kor har reisen deres vore — hittil?",
    conversationPrompt: "Fortel korleis dette rommet har kjennest for deg dei siste dagane.",
    task: "Reflekter over kva dere har delt — kva har gjeve noko?",
    resonanceGoal: "refleksjon",
    systemMessage: "Refleksjon er spegelen som visar kor langt dere har kome — utan ord.",
  },
  {
    day: 13,
    theme: "Blikk",
    phase: "BUILDING_TRUST",
    reflectionQuestion: "Kva trekk ved den andre har du merka — det som fanga deg?",
    conversationPrompt: "Kva har du sett hos den andre som gjer deg nysgjerrig?",
    task: "Nemn eit trekk ved den andre — det kan vera lite, men det må vera verkeleg.",
    resonanceGoal: "oppmerksomhet",
    systemMessage: "Å sjå nokon — verkeleg sjå deira blikk, tonen, stilen — er sjølve grunnlaget.",
  },
  {
    day: 14,
    theme: "Overgang",
    phase: "BUILDING_TRUST",
    reflectionQuestion: "Er du klar for å sjå djupare — eller vil du halda deg i roen lenger?",
    conversationPrompt: "Kva vil du ta med deg inn i neste fase? Kva vil du halde att?",
    task: "Vel éi ting du vil ta med og éi ting du vil halde for deg sjølv.",
    resonanceGoal: "overgang-resonans",
    systemMessage: "14 dagar — du har bygd ein grunn. No kan du velja om du vil gå djupare.",
  },

  // ===== FASE 3: Dypare samtalar (Dag 15-25) =====
  {
    day: 15,
    theme: "Bilete",
    phase: "DEEPER",
    reflectionQuestion: "Bilete er no tilgjengeleg — men berre om du vil. Kva vil du dela?",
    conversationPrompt: "Kva vil du visa — eller vil du halde biletet i tankane?",
    task: "Vel eit bilete eller ei beskriving — det som føler rett for deg no.",
    resonanceGoal: "valgfri sårbarhet",
    systemMessage: "Bilete er no opne. Dette er eit val — aldri eit krav. Del berre om du vil.",
  },
  {
    day: 16,
    theme: "Sårbarhet",
    phase: "DEEPER",
    reflectionQuestion: "Kva er det mest sårbare du har delt med nokon?",
    conversationPrompt: "Fortel om noko som gjer deg sårbar — sjølv å skrive det kjennest trygt for deg.",
    task: "Del noko sårbart — det treng ikkje vera stort, berre sant.",
    resonanceGoal: "sårbarhet-resonans",
    systemMessage: "Sårbarheit er ikkje svakt — det er det sterkaste eit menneske kan visa.",
  },
  {
    day: 17,
    theme: "Livsval",
    phase: "DEEPER",
    reflectionQuestion: "Kva er det viktigaste livet har lært deg — det du aldri vil glo tilbake på?",
    conversationPrompt: "Kva val har forma deg mest?",
    task: "Beskriv eit livsval som endra kva du trur på.",
    resonanceGoal: "verdier-i-praksis",
    systemMessage: "Livsval er stein i vegen dei former terrenget. Å skilja dei med nokon er å visa terreng.",
  },
  {
    day: 18,
    theme: "Drøm",
    phase: "DEEPER",
    reflectionQuestion: "Kva er drøma di — den som kjem sent og går tidleg?",
    conversationPrompt: "Kva drøm vil du aldri fortelje nokon fordi det er for sårbart?",
    task: "Fortel om ei drøm — den som kjem sent og går tidleg.",
    resonanceGoal: "drøm-kompatibilitet",
    systemMessage: "Drømmar er stjerne — dei viser retning. Å dele dei med nokon er å visa stjernekart.",
  },
  {
    day: 19,
    theme: "Tunge stein",
    phase: "DEEPER",
    reflectionQuestion: "Kva bær du på som er tungt — og som ingen veit?",
    conversationPrompt: "Er det noko du bur med? Kva er det?",
    task: "Legg vekk ein tung stein — skriv han ut, del han med den andre.",
    resonanceGoal: "empati-erkjenning",
    systemMessage: "Nokre steinar er tunge berre fordi dei er alene. Å dela dei halverer vekten.",
  },
  {
    day: 20,
    theme: "Nærleik",
    phase: "DEEPER",
    reflectionQuestion: "Kva betyr nærleik for deg — fysisk, emosjonelt, spirituelt?",
    conversationPrompt: "Korlei opplever du nærleik — og kva gjer det med deg?",
    task: "Fortel kva nærleik betyr for deg — i ord, ikkje i bilde.",
    resonanceGoal: "nærleik-kompatibilitet",
    systemMessage: "Nærleik er ikkje avstand — det er tilstadevering. Det finn ein i roen.",
  },
  {
    day: 21,
    theme: "Konflikt",
    phase: "DEEPER",
    reflectionQuestion: "Korlei handterer du uenigheit — i ord, i tonen, i stil?",
    conversationPrompt: "Fortel om korlei du handterer noko som ikkje stemmer mellom dere to.",
    task: "Beskriv korlei du ønskjer å handtera uenigheit — saman med den andre.",
    resonanceGoal: "konflikt-kompatibilitet",
    systemMessage: "Uenigheit er ikkje fare — det er eit skritt mot å forstå kvarandre betre.",
  },
  {
    day: 22,
    theme: "Gje",
    phase: "DEEPER",
    reflectionQuestion: "Kva kan du gje den andre — det ingen annan kan?",
    conversationPrompt: "Kva har du i deg som er unikt — og som du ønskjer å gi?",
    task: "Vel éin ting du kan gje — ei gåve, ei kunnskap, eller berre nærvær.",
    resonanceGoal: "gje-gjensvar",
    systemMessage: "Å gje noko unikt er det same som å koma nær.",
  },
  {
    day: 23,
    theme: "Stille",
    phase: "DEEPER",
    reflectionQuestion: "Kva er det som ikkje treng ord — det dere kan finn i stillhet?",
    conversationPrompt: "Er det noko mellom dere to som ikkje treng seiast?",
    task: "Ver stille saman — det kan vera éin minutt i stillhet med den andre.",
    resonanceGoal: "stillhets-resonans",
    systemMessage: "Noen ting er tydelege i stillheten. La dei vera det.",
  },
  {
    day: 24,
    theme: "Felles",
    phase: "DEEPER",
    reflectionQuestion: "Kva har dere felles — det ingen annan ser?",
    conversationPrompt: "Kva har dere bygt saman — sjølv i dei fyrste dagane?",
    task: "Nemn éitt felles — ein detalj, ein stemning, ein oppleving.",
    resonanceGoal: "felles-resonans",
    systemMessage: "Det felles er eit rom berre to deler — byggt ord for ord, dag for dag.",
  },
  {
    day: 25,
    theme: "Innsikt",
    phase: "DEEPER",
    reflectionQuestion: "Kva har denne reisen lært deg om deg sjølv?",
    conversationPrompt: "Er det noko om deg som har kome til syne — noko du ikkje visste?",
    task: "Reflekter over kva som har endra seg i deg — sjølv litt.",
    resonanceGoal: "sjølv-innsikt",
    systemMessage: "Reise er ikkje berre mellom to menneske — det er mellom kven du var og kven du blir.",
  },

  // ===== FASE 4: Felles reise (Dag 26-30) =====
  {
    day: 26,
    theme: "Bygg",
    phase: "CHECKIN",
    reflectionQuestion: "Kva vil du byggja saman — med den andre?",
    conversationPrompt: "Kva kan vera felles — eit prosjekt, ei rutine, ei tradisjon?",
    task: "Beskriv éitt du vil byggja — ein ting, eit stoff, ein van.",
    resonanceGoal: "felles-bygg",
    systemMessage: "Bygg er det som held rommet i live — etter at dagane er over.",
  },
  {
    day: 27,
    theme: "Vekst",
    phase: "CHECKIN",
    reflectionQuestion: "Kor har du vokse — saman med den andre?",
    conversationPrompt: "Kva har denne reisen gjort med deg? Kva har den endra?",
    task: "Beskriv veksten din — den minste, men den verkelegaste.",
    resonanceGoal: "vekst-resonans",
    systemMessage: "Vekst kjem ikkje av å vera ferdig — det kjem av å vera open for endring.",
  },
  {
    day: 28,
    theme: "Veien vidare",
    phase: "CHECKIN",
    reflectionQuestion: "Kva vil du med denne reisen — etter dei 30 dagane?",
    conversationPrompt: "Fortel om ønsket ditt — fortsetja, pause, eller avslutta?",
    task: "Nemn éitt ønskje for vegen vidare.",
    resonanceGoal: "vegen-vidare-resonans",
    systemMessage: "Vegen vidare er ditt val. Det er aldri feil — berre ditt.",
  },
  {
    day: 29,
    theme: "Takk",
    phase: "CHECKIN",
    reflectionQuestion: "Kva er noko du er takknemleg for frå denne reisen?",
    conversationPrompt: "Fortel den andre noko du er takknemleg for.",
    task: "Skriv ei takk — kort eller lang, det kjem ikkje an. Berre sann.",
    resonanceGoal: "takk-resonans",
    systemMessage: "Takk er ikkje avslutning — det er eit minne om at noko var verkeleg.",
  },
  {
    day: 30,
    theme: "Avslutning",
    phase: "CHECKIN",
    reflectionQuestion: "Kva har denne reisen vore for deg — i éin setning?",
    conversationPrompt: "Kva tek du med deg — og kva la du att?",
    task: "Beskriv reisa di i éin setning — din, din, din.",
    resonanceGoal: "heile-reise-resonans",
    systemMessage: "30 dagar. To menneske. Éi reise. Det er ikkje ende — det er eit kapittel.",
  },
]

async function main() {
  console.log("Seeding 30-dagers reise-innhald...")

  for (const day of journeyContent) {
    await prisma.journeyDayContent.upsert({
      where: { day: day.day },
      update: {
        theme: day.theme,
        phase: day.phase as any,
        reflectionQuestion: day.reflectionQuestion,
        conversationPrompt: day.conversationPrompt,
        task: day.task,
        resonanceGoal: day.resonanceGoal,
        systemMessage: day.systemMessage,
      },
      create: {
        day: day.day,
        theme: day.theme,
        phase: day.phase as any,
        reflectionQuestion: day.reflectionQuestion,
        conversationPrompt: day.conversationPrompt,
        task: day.task,
        resonanceGoal: day.resonanceGoal,
        systemMessage: day.systemMessage,
      },
    })
  }

  console.log("✅ 30 dagar med reise-innhald er seeda.")
}

main()
  .catch((e) => {
    console.error("Seed feil:", e)
    process.exit(1)
  })
  .finally(() => prisma.$disconnect())