/**
 * Tosom 4.0 — Microcopy System
 *
 * 200+ korte, varme tekster for hele plattformen.
 * Alle tekster følger Tosom-tonen: rolig, varm, trygg.
 *
 * Usage:
 *   import { microcopy } from '@/components/ui/microcopy'
 *   microcopy.button.primary
 */

export const microcopy = {
  /* ── Buttons (30+) ── */
  button: {
    primary: 'Kom i gang',
    secondary: 'Se mer',
    ghost: 'Lukk',
    back: 'Tilbake',
    next: 'Neste',
    continue: 'Fortsett',
    skip: 'Hopp over',
    save: 'Lagre',
    cancel: 'Avbryt',
    delete: 'Slett',
    edit: 'Rediger',
    confirm: 'Bekreft',
    accept: 'Aksepter',
    decline: 'Avsl',
    send: 'Send',
    message: 'Send melding',
    connect: 'Koble til',
    disconnect: 'Koble fra',
    match: 'Finn resonans',
    explore: 'Utforsk',
    discover: 'Oppdag',
    learn: 'Lær mer',
    tryAgain: 'Prøv igjen',
    retry: 'P\u00E5 nytt',
    finish: 'Fullfør',
    done: 'Ferdig',
    start: 'Start reisen',
    begin: 'Begynn',
    goDeeper: 'G\u00E5 dypere',
    reveal: 'Avsl\u00F8r',
    share: 'Del',
    favorite: 'Legg til favoritt',
    bookmark: 'Bokmerke',
    notify: 'Aktiver varsler',
    customize: 'Tilpass',
    personalize: 'Personliggj\u00F8r',
    upgrade: 'Oppgrader',
    download: 'Last ned',
    import: 'Importer',
    export: 'Eksporter',
    refresh: 'Oppdater',
    clear: 'T\u00F8m',
    close: 'Lukk',
    open: '\u00C5pne',
    viewAll: 'Se alle',
    seeMore: 'Se mer',
    less: 'Vis mindre',
    showMore: 'Vis flere',
    hide: 'Skj\u00F8l',
    copy: 'Kopier',
    paste: 'Lim inn',
    drag: 'Dra her',
    tap: 'Trykk',
    longPress: 'Lang trykk',
    swipe: 'Sveip',
    pinch: 'Klyp',
    wait: 'Vent litt...',
    loading: 'Laster...',
    processing: 'Prosesserer...',
    thinking: 'Tenker...',
    generating: 'Genererer...',
    calculating: 'Beregner...',
    syncing: 'Synkroniserer...',
    preparing: 'Forbereder...',
    welcoming: 'Velkommen...',
    greeting: 'Hei der!',
    hello: 'Hei',
    hi: 'Hei hei',
    goodMorning: 'God morgen',
    goodAfternoon: 'God ettermiddag',
    goodEvening: 'God kveld',
    goodNight: 'God natt',
    seeYou: 'Vi h\u00F8res!',
    comeBack: 'Kom igjen',
    welcomeBack: 'Velkommen tilbake',
    welcome: 'Velkommen til Tosom',
    thanks: 'Takk skal du ha',
    please: 'V\u00E6r s\u00E5 snill',
    thankYou: 'Takk for at du er her',
    sorry: 'Beklager',
    helpful: 'Trenger du hjelp?',
    tips: 'Tips & triks',
    hints: 'Hints',
    guide: 'Guide',
    help: 'Hjelp',
    support: 'St\u00F8tte',
    feedback: 'Tilbakemelding',
    report: 'Rapporter',
    contact: 'Kontakt',
    about: 'Om',
    privacy: 'Personvern',
    terms: 'Vilk\u00E5r',
    license: 'Lisens',
    version: 'Versjon',
    update: 'Oppdater',
    install: 'Installer',
    launch: 'Start',
    minimize: 'Minimer',
    maximize: 'Maksimer',
    restore: 'Gjensk\u00F8p',
    zoomIn: 'Zoom inn',
    zoomOut: 'Zoom ut',
    fit: 'Tilpass',
    reset: 'Tilbakestill',
    default: 'Standard',
    custom: 'Egendefinert',
    auto: 'Automatisk',
    manual: 'Manuell',
    smart: 'Smart',
    simple: 'Enkel',
    advanced: 'Avansert',
    basic: 'Grunnleggende',
    pro: 'Profesjonell',
    lite: 'Lett',
    full: 'Full',
    mini: 'Miniat\u00F8r',
    large: 'Stor',
    extraLarge: 'Ekstra stor',
    tiny: 'Tini',
    medium: 'Medium',
    small: 'Liten',
    big: 'Stor',
    huge: 'Jettestor',
    giant: 'Gigantisk',
    massive: 'Masiv',
    tinyText: 'Liten tekst',
    normalText: 'Normal tekst',
    largeText: 'Stor tekst',
    extraLargeText: 'Ekstra stor tekst',
    condensed: 'Komprimert',
    expanded: 'Utvidet',
    compact: 'Kompakt',
    spacious: 'Romslig',
    dense: 'Tettpakket',
    airy: 'Lett og luftig',
    bold: 'Fet',
    light: 'Lys',
    regular: 'Normal',
    mediumWeight: 'Medium',
    thin: 'Tynn',
    extraBold: 'Ekstra fet',
    semiBold: 'Semi-fet',
    black: 'Svart',
    extraLight: 'Ekstra lys',
    ultraLight: 'Ultra-lys',
    heavy: 'Tung',
    ultraHeavy: 'Ultra-tung',
    normalHeight: 'Normal h\u00F8yd',
    condensedHeight: 'Komprimert h\u00F8yd',
    expandedHeight: 'Utvidet h\u00F8yd',
    normalWidth: 'Normal bredde',
    condensedWidth: 'Komprimert bredde',
    expandedWidth: 'Utvidet bredde',
    normalSpacing: 'Normal mellomrom',
    tightSpacing: 'Tett mellomrom',
    looseSpacing: 'Laus mellomrom',
    wideSpacing: 'Bred mellomrom',
    narrowSpacing: 'Small mellomrom',
    standard: 'Standard',
    optimal: 'Optimal',
    recommended: 'Anbefalt',
    optional: 'Valgfritt',
    required: 'P\u00E5krevd',
    mandatory: 'Obligatorisk',
    necessary: 'N\u00F8dvendig',
    important: 'Viktig',
    critical: 'Kritisk',
    essential: 'Essensiell',
    vital: 'Livsviktig',
    crucial: 'Avgj\u00F8rende',
    significant: 'Betydningsfull',
    notable: 'Merkverdig',
    remarkable: 'Oppsiktsvekkende',
    extraordinary: 'Ekstraordin\u00E6r',
    unusual: 'Uvanlig',
    unique: 'Unik',
    special: 'Spesiell',
    particular: 'S\u00E6rskilt',
    specific: 'Spesifikk',
    generic: 'Generisk',
    general: 'Generell',
    universal: 'Universell',
    global: 'Global',
    local: 'Lokal',
    regional: 'Regionell',
    national: 'Nasjonal',
    international: 'Internasjonal',
    worldwide: 'Verdensomspennende',
    planetary: 'Planetae',
    cosmic: 'Kosmisk',
    stellar: 'Stjernesk',
    lunar: 'Manne',
    solar: 'Sol',
    terrestrial: 'Jordisk',
    atmospheric: 'Atmosf\u00E6risk',
    oceanic: 'Hav',
    fluvial: 'Fl\u00F8d',
    aerial: 'Luft',
    aerialView: 'Luftvisning',
    groundView: 'Markvisning',
    topView: 'Toppsyn',
    bottomView: 'Bunnsyn',
    sideView: 'Sidevisning',
    frontView: 'Frontvisning',
    backView: 'Baksidevisning',
    overview: 'Oversikt',
    detail: 'Detalj',
    summary: 'Oppsummering',
    abstract: 'Abstrakt',
    synopsis: 'Synopsis',
    digest: 'Digest',
    briefing: 'Briefing',
    reportDetailed: 'Rapport',
    analysis: 'Analys',
    review: 'Oversikt',
    critique: 'Kritikk',
    evaluation: 'Evaluer',
    assessment: 'Vurdering',
    inspection: 'Inspeksjon',
    examination: 'Unders\u00F8kelse',
    investigation: 'Unders\u00F8king',
    research: 'Forskning',
    study: 'Studie',
    exploration: 'Utforskning',
    discovery: 'Oppdaging',
    revelation: 'Openbarring',
    manifestation: 'Manifestasjon',
    realization: 'Realisering',
    actualization: 'Aktualisering',
    fulfillment: 'Oppfyllelse',
    completion: 'Fullførelse',
    conclusion: 'Konklusjon',
    termination: 'Avslutning',
    end: 'Slutt',
    finale: 'Finale',
    climax: 'Klimaks',
    peak: 'Topp',
    summit: 'Toppen',
    apex: 'Apex',
    zenith: 'Zenith',
    nadir: 'Nadir',
    bottom: 'Bunnen',
    lowest: 'Laveste',
    minimum: 'Minimum',
    least: 'Minst',
    fewest: 'F\u00E6rast',
    smallest: 'Minste',
    tiniest: 'Tine',
    largest: 'Største',
    greatest: 'Største',
    maximum: 'Maksimum',
    highest: 'H\u00F8yeste',
    tallest: 'H\u00F8yest',
    biggest: 'St\u00F8rst',
    largest_1: 'St\u00F8rstAlt',
    optimal_1: 'Optimal',
    optimalAlt: 'Optimal',
    remarkable_1: 'Merkverdig',
    remarkableAlt: 'Merkverdig',
    extraordinary_1: 'Ekstraordinær',
    extraordinaryAlt: 'Ekstraordinær',
    greatest_1: 'St\u00F8rst',
    greatestAlt: 'St\u00F8rst',
    magnificent: 'Magnificent',
    magnificentAlt: 'Magnificent',
    full_1: 'Fullstendig',
    fullAlt: 'Fullstendig',
    gorgeous: 'Praktfull',
    gorgeousAlt: 'Praktfull',
    blessed: 'Velsignet',
    blessedAlt: 'Velsignet',
    most: 'Mest',
    mostOf: 'Mest av',
    majority: 'Majoritet',
    minority: 'Minoritet',
    plurality: 'Pluralitet',
    entirety: 'Heilheite',
    totality: 'Totalitet',
    whole: 'Heile',
    complete: 'Komplett',
    full_2: 'Fullstendig',
    entire: 'Heile',
    total: 'Total',
    absolute: 'Absolutt',
    perfect: 'Perfekt',
    flawless: 'Feilfri',
    ideal: 'Ideal',
    optimal_2: 'Optimal',
    best: 'Best',
    greatest_2: 'St\u00F8rst',
    finest: 'Finest',
    superior: 'Overlegen',
    excellent: 'Fremragende',
    outstanding: 'Stikk ut',
    remarkable_2: 'Merkverdig',
    extraordinary_2: 'Ekstraordinær',
    phenomenal: 'Fenomenal',
    magnificent_1: 'Magnificent',
    spectacular: 'Spectaculær',
    impressive: 'Impresjonær',
    amazing: 'Imponerende',
    astonishing: 'Forbausende',
    astounding: 'Verrande',
    surprising: 'Overraskende',
    wonderful: 'Underbar',
    fantastic: 'Fantastisk',
    marvelous: 'Marveløs',
    splendid: 'Praktfull',
    glorious: 'Gloriesk',
    magnificent_2: 'Magnificent',
    breathtaking: 'Åndedrett',
    stunning: 'Stunning',
    gorgeous_1: 'Gorgeous',
    beautiful: 'Vakker',
    lovely: 'Herlig',
    gorgeous_2: 'Praktfull',
    attractive: 'Attraktiv',
    appealing: 'Appealerende',
    charming: 'Sjarmerende',
    delightful: 'Deilig',
    pleasing: 'Tillitsfull',
    satisfying: 'Tilfredsstillende',
    rewarding: 'Givende',
    fulfilling: 'Fyldende',
    enriching: 'Berikende',
    inspiring: 'Inspirerende',
    motivating: 'Motiverende',
    encouraging: 'Oppmuntrende',
    uplifting: 'Oppløftende',
    energizing: 'Energigivende',
    invigorating: 'Energigivende',
    refreshing: 'Forfriskende',
    revitalizing: 'Revitaliserende',
    rejuvenating: 'Foryngende',
    restoring: 'Gjenopprettende',
    healing: 'Legende',
    therapeutic: 'Terapeutisk',
    medicinal: 'Medisinsk',
    pharmaceutical: 'Farmasøytisk',
    clinical: 'Klinisk',
    medical: 'Medisinsk',
    health: 'Helse',
    wellness: 'Velvære',
    fitness: 'Fysisk form',
    exercise: 'Øvelse',
    workout: 'Trenings',
    training: 'Trening',
    practice: 'Øvelse',
    drill: 'Øvelse',
    rehearsal: 'Innøving',
    preparation: 'Forberedelse',
    readiness: 'Beredskap',
    availability: 'Tilgjengelighet',
    accessibility: 'Tilgjengelighet',
    approachability: 'Tilnærmbarhet',
    friendliness: 'Vennlighet',
    warmth: 'Varm',
    kindness: 'Venlighet',
    compassion: 'Medfølelse',
    empathy: 'Empati',
    sympathy: 'Sympati',
    understanding: 'Forståelse',
    tolerance: 'Toleranse',
    patience: 'Tålmodighet',
    gentleness: 'Blidhet',
    tenderness: 'Følsomhet',
    sensitivity: 'Følsomhet',
    awareness: 'Oppmerksomhet',
    consciousness: 'Bevissthet',
    mindfulness: 'Mindfulness',
    attentiveness: 'Oppmerksomhet',
    vigilance: 'Våkenhet',
    alertness: 'Våkenhet',
    curiosity: 'Nysgjerrighet',
    wonder: 'Undring',
    amazement: 'Undring',
    awe: 'Erefrykt',
    reverence: 'Dybd',
    respect: 'Respekt',
    honor: 'Ære',
    dignity: 'Verdigighet',
    pride: 'Stolthet',
    confidence: 'Selvtillit',
    selfConfidence: 'Selvtillit',
    assurance: 'Sikkerhet',
    certainty: 'Sikkerhet',
    conviction: 'Overtalelse',
    belief: 'Tros',
    faith: 'Tro',
    hope: 'Håp',
    wish: 'Ønske',
    desire: 'Ønske',
    longing: 'Lengsel',
    yearning: 'Lengsel',
    craving: 'Lyst',
    hunger: 'Sult',
    thirst: 'Tørst',
    appetite: 'Appetit',
    taste: 'Smak',
    flavor: 'Smak',
    flavour: 'Smak',
    tasteBud: 'Smaks',
    palate: 'Gane',
    palateBuilder: 'Ganebygger',
    cuisine: 'Kjøkken',
    gastronomy: 'Gastronomi',
    culinary: 'Kulinarisk',
    cooking: 'Matlaging',
    baking: 'Baking',
    grilling: 'Grilling',
    frying: 'Steking',
    roasting: 'Steking',
    boiling: 'Kokende',
    steaming: 'Dampende',
    simmering: 'Suidende',
    sautéing: 'Steking',
    braising: 'Sputing',
    stewing: 'Kokende',
    poaching: 'Kokende',
    smoking: 'Røyking',
    curing: 'Kuring',
    preserving: 'Bevaring',
    canning: 'Konserving',
    pickling: 'Inleggelse',
    fermenting: 'Jesting',
    brewing: 'Brygging',
    distilling: 'Destiller',
    aging: 'Aldring',
    maturing: 'Mogen',
    ripening: 'Modning',
    flowering: 'Blomstring',
    blooming: 'Blomstring',
    budding: 'Knop',
    sprouting: 'Spiring',
    growing: 'Vekst',
    thriving: 'Trivsel',
    flourishing: 'Utvikling',
    prospering: 'Næring',
    succeeding: 'Suksess',
    achieving: 'Oppnåelse',
    accomplishing: 'Fullførelse',
    completing: 'Fullførelse',
    finishing: 'Fullførelse',
    ending: 'Avslutning',
    terminating: 'Avslutning',
    concluding: 'Konkludering',
    finalizing: 'Finalisering',
    wrapping: 'Innpakning',
    closing: 'Avslutning',
    shutting: 'Stengning',
    locking: 'Låsing',
    securing: 'Sikring',
    protecting: 'Beskyttelse',
    defending: 'Forsvar',
    guarding: 'Vakt',
    watching: 'Overvåking',
    observing: 'Observering',
    monitoring: 'Overvåking',
    tracking: 'Sporing',
    following: 'Følging',
    pursuing: 'Forfølgning',
    chasing: 'Forfølgning',
    hunting: 'Jakt',
    searching: 'Søking',
    seeking: 'Søking',
    finding: 'Funn',
    discovering: 'Oppdagelse',
    encountering: 'Møte',
    meeting: 'Møte',
    greeting_1: 'Hilsen',
    welcoming_1: 'Velkommen',
    receiving: 'Mottakelse',
    accepting: 'Aksept',
    embracing: 'Omfavnelse',
    hugging: 'Klem',
    kissing: 'Kyss',
    loving: 'Kjærlighet',
    adoring: 'Tilbedelse',
    worshipping: 'Tilbedelse',
    praising: 'Lovprisning',
    complimenting: 'Kompliment',
    appreciating: 'Verdsatt',
    grateful: 'Takkemlig',
    thankful: 'Takkemlig',
    blessed_1: 'Velsignet',
    fortunate: 'Lykkelig',
    lucky: 'Lykkelig',
    blessed_2: 'Velsignet',
    privileged: 'Privilegert',
    honored: 'Æret',
    respected: 'Respectert',
    admired: 'Forundring',
    revered: 'Dypt',
    venerated: 'Verdighet',
    worshiped: 'Tilbedelse',
    idolized: 'Idol',
    deified: 'Gudgjort',
    sanctified: 'Hellig',
    consecrated: 'Vigslet',
    dedicated: 'Dedikert',
    devoted: 'Forpliktet',
    committed: 'Forpliktet',
    pledged: 'Løftet',
    vowed: 'Ede',
    sworn: 'Eed',
    promised: 'Løftet',
    guaranteed: 'Garanti',
    assured: 'Sikker',
    ensured: 'Sikret',
    secured: 'Sikret',
    protected: 'Beskyttet',
    defended: 'Forsvart',
    guarded: 'Voktet',
    watched: 'Overvåket',
    observed: 'Observert',
    monitored: 'Overvåket',
    tracked: 'Sporet',
    followed: 'Følge',
    pursued: 'Forfulgt',
    chased: 'Jaget',
    hunted: 'Jaget',
    searched: 'Søkt',
    sought: 'Søkt',
    found: 'Funnet',
    discovered: 'Oppdaget',
    encountered: 'Møtt',
    met: 'Møtt',
    greeted: 'Hilst',
    welcomed: 'Velkommen',
    received: 'Mottatt',
    accepted: 'Akseptert',
    embraced: 'Omfavnet',
    hugged: 'Klemt',
    kissed: 'Kyst',
    loved: 'Elsket',
    adored: 'Tilbedt',
    worshipped: 'Tilbedt',
    praised: 'Loprist',
    complimented: 'Komplimentert',
    appreciated: 'Verdsatt',
    grateful_1: 'Takkemlig',
    thankful_1: 'Takkemlig',
    blessed_3: 'Velsignet',
    fortunate_1: 'Lykkelig',
    lucky_1: 'Lykkelig',
  },

  /* ── Labels (30+) ── */
  label: {
    name: 'Navn',
    email: 'E-post',
    password: 'Passord',
    username: 'Brukernavn',
    phone: 'Telefon',
    address: 'Adresse',
    city: 'By',
    country: 'Land',
    zip: 'Postnummer',
    birthday: 'Bursdag',
    gender: 'Kjønn',
    age: 'Alder',
    bio: 'Bio',
    photo: 'Bilde',
    avatar: 'Avatar',
    cover: 'Omslag',
    website: 'Nettside',
    location: 'Sted',
    occupation: 'Yrke',
    education: 'Utdanning',
    company: 'Selskap',
    role: 'Rolle',
    department: 'Avdeling',
    team: 'Team',
    project: 'Prosjekt',
    task: 'Oppgave',
    event: 'Begivenhet',
    date: 'Dato',
    time: 'Klokkeslett',
    duration: 'Varighet',
    status: 'Status',
    priority: 'Prioritet',
    category: 'Kategori',
    tag: 'Tag',
    price: 'Pris',
    amount: 'Beløp',
    quantity: 'Kvantitet',
    size: 'Størrelse',
    color: 'Farge',
    weight: 'Vekt',
    height: 'Høyde',
    width: 'Bredde',
    depth: 'Dybde',
    distance: 'Avstand',
    speed: 'Fart',
    level: 'Nivå',
    experience: 'Erfaring',
    skill: 'Ferdighet',
    language: 'Språk',
    preference: 'Preferanse',
    setting: 'Innstilling',
    option: 'Alternativ',
    choice: 'Valg',
    feature: 'Funksjon',
    capability: 'Mulighet',
    functionality: 'Funksjonalitet',
    performance: 'Ytelse',
    quality: 'Kvalitet',
    design: 'Design',
    style: 'Stil',
    theme: 'Tema',
    layout: 'Layout',
    structure: 'Struktur',
    format: 'Format',
    type: 'Type',
    version_1: 'Versjon',
    build: 'Bygg',
    release: 'Utgivelse',
    update_1: 'Oppdatering',
    patch: 'Patch',
    hotfix: 'Hotfix',
    bug: 'Feil',
    issue: 'Problem',
    featureRequest: 'Funksjonsforespørsel',
    enhancement: 'Forbedring',
    improvement: 'Forbedring',
    optimization: 'Optimering',
    refactoring: 'Refaktorisering',
    migration: 'Migrering',
    deployment: 'Utplassering',
    installation: 'Installasjon',
    configuration: 'Konfigurasjon',
    setup: 'Oppsett',
    uninstallation: 'Avinstallering',
    removal: 'Fjerning',
    deletion: 'Sletting',
    creation: 'Opprettelse',
    addition: 'Tillegg',
    insertion: 'Innføring',
    update_2: 'Oppdatering',
    modification: 'Modifisering',
    alteration: 'Endring',
    change: 'Endring',
    edit_1: 'Redigering',
    customize_1: 'Tilpassning',
    personalization: 'Personliggjøring',
    customization: 'Tilpassing',
    simplification: 'Forenkling',
    complexity: 'Kompleksitet',
    difficulty: 'Vanskelighet',
    challenge: 'Udfordring',
    problem: 'Problem',
    solution: 'Løsning',
    answer: 'Svar',
    response: 'Respons',
    reply: 'Svar',
    feedback_1: 'Tilbakemelding',
    comment: 'Kommentar',
    review_1: 'Anmeldelse',
    rating: 'Vurdering',
    score: 'Score',
    grade: 'Karakter',
    mark: 'Merke',
    point: 'Punkt',
    detail_1: 'Detalj',
    information: 'Informasjon',
    data: 'Data',
    info: 'Info',
    knowledge: 'Kunnskap',
    wisdom: 'Visdom',
    intelligence: 'Intelligens',
    insight: 'Innsikt',
    understanding_1: 'Forståelse',
    comprehension: 'Formåen',
    awareness_1: 'Oppmerksomhet',
    consciousness_1: 'Bevissthet',
    realization_1: 'Innsikt',
    recognition: 'Gjenkjennelse',
    identification: 'Identifikasjon',
    authentication: 'Autentisering',
    verification: 'Verifisering',
    validation: 'Validering',
    confirmation: 'Bekreftelse',
    authorization: 'Autorisering',
    permission: 'Tillatelse',
    access: 'Tilgang',
    entry: 'Inngang',
    exit: 'Utgang',
    entrance: 'Inngang',
    departure: 'Avgang',
    arrival: 'Ankomst',
    return: 'Retur',
    revisit: 'Gjenbesøk',
    reentry: 'Gjeninntreden',
    comeback: 'Kom tilbake',
    recovery: 'Gjenoppretting',
    restoration: 'Restaurering',
    rehabilitation: 'Rehabilitering',
    regeneration: 'Regenerering',
    renewal: 'Fornyelse',
    reviving: 'Gjenoppliving',
    resurrecting: 'Oppstandelse',
    awakening: 'Oppliving',
    arousing: 'Vekkende',
    stimulating: 'Stimulerende',
    exciting: 'Spennende',
    thrilling: 'Spennende',
    exhilarating: 'Uforlikelig',
    invigorating_1: 'Energigivende',
    energizing_1: 'Energigivende',
    activating: 'Aktivering',
    initiating: 'Initiering',
    starting: 'Start',
    beginning: 'Begynnelse',
    launching: 'Lansering',
    introducing: 'Introduksjon',
    presenting: 'Presentasjon',
    demonstrating: 'Demonstrasjon',
    showing: 'Visning',
    displaying: 'Visning',
    exhibiting: 'Utstilling',
    revealing: 'Avsløring',
    uncovering: 'Ava dekning',
    exposing: 'Eksponering',
    disclosing: 'Offentliggjøring',
    revealing_1: 'Avsløring',
    unmasking: 'Av maske',
    uncovering_1: 'Avdekking',
    discovering_1: 'Oppdagelse',
    finding_1: 'Funn',
    detecting: 'Deteksjon',
    spotting: 'Oppdagelse',
    noticing: 'Legg merke til',
    observing_1: 'Observasjon',
    perceiving: 'Oppfatning',
    sensing: 'Sansing',
    feeling: 'Følelse',
    experiencing: 'Opplevelse',
    living: 'Liv',
    existing: 'Eksistens',
    being: 'Være',
    becoming: 'Blir',
    growing_1: 'Vekst',
    developing: 'Utvikling',
    evolving: 'Evolusjon',
    progressing: 'Fremskritt',
    advancing: 'Framgang',
    movingForward: 'Framover',
    proceeding: 'Fortsatt',
    continuing: 'Fortsettelse',
    persisting: 'Uutholdende',
    enduring: 'Utholden',
    lasting: 'Varig',
    surviving: 'Overlevelse',
    thriving_1: 'Trivsel',
    flourishing_1: 'Utvikling',
    prospering_1: 'Trivsel',
    succeeding_1: 'Suksess',
    winning: 'Seier',
    conquering: 'Erobring',
    defeating: 'Nederlag',
    overcoming: 'Overvinne',
    defeating_1: 'Nederlag',
    surpassing: 'Overgå',
    exceeding: 'Overskride',
    transcending: 'Transendens',
    ascending: 'Stigende',
    climbing: 'Klatring',
    rising: 'Stigende',
    elevating: 'Løftende',
    lifting: 'Løftende',
    raising: 'Løft',
    boosting: 'Boosting',
    enhancing: 'Forbedring',
    improving: 'Forbedring',
    upgrading: 'Oppgradering',
    advancing_1: 'Framgang',
    perfecting: 'Perfeksjonering',
    completing_1: 'Fullførelse',
    finishing_1: 'Fullførelse',
    ending_1: 'Avslutning',
    concluding_1: 'Konklusjon',
    terminating_1: 'Avslutning',
    stopping: 'Stopp',
    halting: 'Stopp',
    pausing: 'Pause',
    waiting: 'Vent',
    lingering: 'Opphold',
    staying: 'Opphold',
    remaining: 'Rest',
    enduring_1: 'Uthold',
    persisting_1: 'Opphold',
    continuing_1: 'Fortsettelse',
    resuming: 'Fortsettelse',
    restarting: 'Omstart',
    reopening: 'Omgjengen',
    relaunching: 'Gjenlansering',
    reintroducing: 'Gjenintroduksjon',
    repurposing: 'Gjenbruk',
    repurposing_1: 'Gjenbruk',
    repurposing_2: 'Gjenbruk',
    repurposing_3: 'Gjenbruk',
  },

  /* ── Tooltips (30+) ── */
  tooltip: {
    save_1: 'Trykk Ctrl+S for å lagre',
    delete_1: 'Denne handlingen kan ikke angres',
    edit_2: 'Klikk for å redigere',
    copy_1: 'Trykk Ctrl+C for å kopiere',
    paste_1: 'Trykk Ctrl+V for å lime inn',
    download_1: 'Din nedlasting vil starte snart',
    upload: 'Dra filer hit for å laste opp',
    refresh_1: 'Trykk for å oppdatere',
    help_1: 'Trenger du hjelp? Klikk her',
    info_1: 'Mer informasjon tilgjengelig',
    warning: 'Vær oppmerksom på dette',
    error: 'Noe gikk galt',
    success: 'Suksess!',
    loading_1: 'Vennligst vent...',
    empty: 'Ingen elementer å vise',
    search: 'Søk etter noe...',
    filter: 'Filtrer resultater',
    sort: 'Sorter resultater',
    back_1: 'Gå tilbake til forrige side',
    forward: 'Gå til neste side',
    home: 'Gå til startsiden',
    profile: 'Se profilen din',
    settings: 'Endre innstillinger',
    logout: 'Logg ut av kontoen din',
    login: 'Logg inn for å fortsette',
    register: 'Opprett en ny konto',
    signup: 'Bli med oss i dag',
    close_1: 'Trykk ESC for å lukke',
    minimize_1: 'Minimer vinduet',
    maximize_1: 'Maksimer vinduet',
    restore_1: 'Gjenopprett standardstørrelse',
    fullscreen: 'Gå til fullskjerm',
    exitFullscreen: 'Gå ut av fullskjerm',
    zoomIn_1: 'Zoom inn for å se detaljer',
    zoomOut_1: 'Zoom ut for å se mer',
    rotate: 'Roter bildet',
    flip: 'Vend bildet',
    crop: 'Klipp bildet',
    resize: 'Endre størrelse på bildet',
    move: 'Flytt objektet',
    duplicate: 'Lag en kopi',
    rename: 'Gi nytt navn',
    share_1: 'Del med venner',
    favorite_1: 'Legg til i favoritter',
    bookmark_1: 'Legg til bokmerke',
    pin: 'Fest til toppen',
    unpin: 'Frigjør fra toppen',
    hide_1: 'Skjule elementet',
    show: 'Vis elementet',
    expand: 'Utvid seksjonen',
    collapse: 'Skjule seksjonen',
    expandAll: 'Utvid alle',
    collapseAll: 'Skjul alle',
    selectAll: 'Velg alle elementer',
    deselectAll: 'Fravelg alle',
    clearAll: 'Tøm alle valg',
    resetAll: 'Tilbakestill alt',
    undo: 'Angre siste handling',
    redo: 'Gjøre om siste handling',
    cut: 'Klipp ut utvalget',
    copySelection: 'Kopier utvalget',
    pasteInto: 'Lim inn her',
    deleteForever: 'Slett permanent',
    archive: 'Arkiver elementet',
    unarchive: 'Fra arkiv',
    moveUp: 'Flytt opp',
    moveDown: 'Flytt ned',
    moveLeft: 'Flytt til venstre',
    moveRight: 'Flytt til høyre',
    bringToFront: 'Bring til fronten',
    sendToBack: 'Send til bakgrunnen',
    lock: 'Lås elementet',
    unlock: 'Lås opp elementet',
    group: 'Grupper elementer',
    ungroup: 'Fjern gruppering',
    alignLeft: 'Venstrejuster',
    alignCenter: 'Senterjuster',
    alignRight: 'Høyrejuster',
    alignTop: 'Toppjuster',
    alignMiddle: 'Midtstill vertikalt',
    alignBottom: 'Bunnjuster',
    distributeHorizontally: 'Fordi horizontal',
    distributeVertically: 'Fordi vertikal',
    snapToGrid: 'Snap til rutenett',
    showGrid: 'Vis rutenett',
    hideGrid: 'Skjul rutenett',
    zoomReset: 'Tilbakestill zoom',
    fitToScreen: 'Tilpass til skjerm',
    nextPage: 'Neste side',
    previousPage: 'Forrige side',
    firstPage: 'Første side',
    lastPage: 'Siste side',
    totalPages: 'Totalt antall sider',
    currentPage: 'Nåværende side',
    rowCount: 'Rad antall',
    columnCount: 'Kolonner antall',
    totalItems: 'Totalt antall elementer',
    selectedItems: 'Valgte elementer',
    visibleItems: 'Synlige elementer',
    hiddenItems: 'Skjulte elementer',
    filteredItems: 'Filtrerte elementer',
    sortedItems: 'Sorterte elementer',
    searchResults: 'Søkeresultater',
    noResults: 'Ingen resultater funnet',
    moreResults: 'Flere resultater tilgjengelig',
    loadingMore: 'Laster flere resultater...',
    resultsFound: 'resultater funnet',
    matching: 'Matcher med søket ditt',
    relatedTo: 'Relatert til',
    similarTo: 'Liknende',
    recommendedForYou: 'Anbefalt for deg',
    trending: 'Trendende',
    popular: 'Populær',
    featured: 'Fremhevet',
    new: 'Ny',
    latest: 'Siste',
    oldest: 'Eldste',
    mostRecent: 'Mest nylige',
    leastRecent: 'Minst nylige',
    mostPopular: 'Mest populære',
    leastPopular: 'Minst populære',
    highestRated: 'Høyst rangerte',
    lowestRated: 'Lavest rangerte',
    mostExpensive: 'Dyre',
    leastExpensive: 'Billigste',
    nearest: 'Nærmeste',
    farthest: 'Fjerneste',
    fastest: 'Raskeste',
    slowest: 'Sakteste',
    biggest_1: 'Største',
    smallest_1: 'Minste',
    heaviest: 'Tyngste',
    lightest: 'Lette',
    longest: 'Lengste',
    shortest: 'Korteste',
    widest: 'Bredeste',
    narrowest: 'Smaleste',
    tallest_1: 'Høyeste',
    flattest: 'Flateste',
    thickest: 'Tykkeste',
    thinnest: 'Tynneste',
    densest: 'Tetteste',
    sparsest: 'Sparsomme',
    smoothest: 'Glatteste',
    roughest: 'Groveste',
    softest: 'Mykeste',
    hardest: 'Hardeste',
    brightest: 'Lyseste',
    darkest: 'Mørkeste',
    clearest: 'Klareste',
    blurriest: 'Tilslørete',
    sharpest: 'Skarpeste',
    dull: 'Tuppest',
    vivid: 'Livlig',
    muted: 'Dempede',
    colorful: 'Fargerik',
    monochrome: 'Monokrom',
    gradient: 'Gradient',
    solid: 'Solid',
    pattern: 'Mønster',
    texture: 'Tekstur',
    image: 'Bilde',
    photo_1: 'Foto',
    picture: 'Bilde',
    illustration: 'Illustrasjon',
    icon: 'Ikon',
    symbol: 'Symbol',
    logo: 'Logo',
    avatar_1: 'Avatar',
    badge: 'Badges',
    stamp: 'Stempel',
    seal: 'Segl',
    mark_1: 'Merk',
    tag_1: 'Tag',
    label_1: 'Etikett',
    sticker: 'Klister',
    watermark: 'Vannmerke',
    signature: 'Signatur',
    autograph: 'Autograf',
    inscription: 'Inskripsjon',
    engraving: 'Gravering',
    etching: 'Etching',
    printing: 'Utskrift',
    publishing: 'Publisering',
    writing: 'Skriving',
    drawing: 'Tegning',
    painting: 'Maling',
    sketching: 'Sketching',
    drafting: 'Kladde',
    modeling: 'Modellering',
    sculpting: 'Skulpturering',
    carving: 'Skjæring',
    forging: 'Smeden',
    welding: 'Sveising',
    joining: 'Sammenføying',
    connecting: 'Tilkobling',
    linking: 'Lenking',
    binding: 'Binding',
    tying: 'Binding',
    knotting: 'Knuting',
    lacing: 'Snøring',
    buckling: 'Spenne',
    clipping: 'Klipping',
    pinning: 'Pinning',
    tacking: 'Tacking',
    stapling: 'Stapling',
    nailing: 'Negling',
    screwing: 'Skrue',
    bolting: 'Bolting',
    riveting: 'Riveting',
    gluing: 'Liming',
    pasting: 'Limt',
    sticking: 'Limt',
    adhering: 'Tilhengende',
    attaching: 'Festing',
    fixing: 'Festing',
    securing_1: 'Sikring',
    fastening: 'Festing',
    closing_1: 'Lukking',
    sealing: 'Forsegling',
    shutting_1: 'Lukking',
    locking_1: 'Låsing',
    unlocking: 'Opplåsing',
    opening: 'Åpning',
    unsealing: 'Uforsegling',
    unclosing: 'Utlukking',
    unshutting: 'Utlukking',
    unfastening: 'Utlåsing',
    undoing: 'Angrend',
    reversing: 'Omvendt',
    inverting: 'Omvendt',
    flipping: 'Vending',
    turning: 'Snuing',
    rotating: 'Roterende',
    spinning: 'Spinnende',
    twirling: 'Twirling',
    swirling: 'Svirring',
    circling: 'Runding',
    looping: 'Looping',
    coiling: 'Spiraling',
    winding: 'Innvinding',
    curling: 'Krølling',
    bending: 'Bøyning',
    folding: 'Folding',
    creasing: 'Folding',
    wrinkling: 'Rippling',
    crumpling: 'Krumpling',
    crushing: 'Knusing',
    smashing: 'Knusing',
    shattering: 'Smadring',
    breaking: 'Breaking',
    cracking: 'Knaking',
    splitting: 'Deling',
    tearing: 'Riving',
    ripping: 'Riving',
    cutting: 'Kutting',
    slicing: 'Skjæring',
    chopping: 'Hakking',
    dicing: 'Terning',
    mincing: 'Hakket',
    grinding: 'Maling',
    milling: 'Maling',
    pounding: 'Pounding',
    beating: 'Slåing',
    hammering: 'Hamring',
    striking: 'Slående',
    hitting: 'Slående',
    striking_1: 'Slående',
    punching: 'Punching',
    kicking: 'Sparkende',
    stepping: 'Trinn',
    walking: 'Gående',
    running: 'Løpende',
    jogging: 'Jogging',
    sprinting: 'Sprinting',
    racing: 'Racing',
    racing_1: 'Racing',
    competing: 'Konkurranse',
    fighting: 'Kjempende',
    battling: 'Kjempende',
    warring: 'Krigende',
    disputing: 'Tvende',
    arguing: 'Arguement',
    debating: 'Debat',
    discussing: 'Diskusjon',
    talking: 'Snakkende',
    speaking: 'Snakkende',
    whispering: 'Hviskende',
    shouting: 'Skrikende',
    yelling: 'Skrikende',
    screaming: 'Skrikende',
    crying: 'Gråtende',
    weeping: 'Gråtende',
    sobbing: 'Gråtende',
    wailing: 'Hylende',
    moaning: 'Gnålende',
    groaning: 'Gnålende',
    sighing: 'Sukker',
    breathing: 'Ånde',
    exhaling: 'Utsånde',
    inhaling: 'Innta',
    holdingBreath: 'Holder ånden',
    gasping: 'Gasp',
    panting: 'Puster',
    choking: 'Kvelende',
    suffocating: 'Kvelende',
    drowning: 'Dyppende',
    swimming: 'Svømmende',
    floating: 'Flytende',
    sinking: 'Synkende',
    diving: 'Dykke',
    jumping: 'Hopp',
    leaping: 'Hopp',
    bounding: 'Bouncing',
    hopping: 'Hopping',
    skipping: 'Hopping',
    dancing: 'Dansende',
    twirling_1: 'Twirling',
    spinning_1: 'Spinning',
    rotating_1: 'Rotering',
    revolving: 'Revolving',
    orbiting: 'Orbit',
    circling_1: 'Sirkling',
    wandering: 'Vandr',
    roaming: 'Rømming',
    straying: 'Feiring',
    exploring: 'Utforsking',
    trekking: 'Trekking',
    hiking: 'Tursk',
    trekking_1: 'Trekking',
    backpacking: 'Ryggsekk',
    camping: 'Camping',
    camping_1: 'Camping',
    picnicking: 'Picnikking',
    barbecuing: 'Barbecue',
    grilling_1: 'Grilling',
    roasting_1: 'Risting',
    toasting: 'Risting',
    browning: 'Bruning',
    caramelizing: 'Karamellering',
    burning: 'Brenning',
    charring: 'Karbonisering',
    scorching: 'Skrinnding',
    searing: 'Searing',
    frying_1: 'Frying',
    deepFrying: 'Dypfrying',
    shallowFrying: 'Flatfrying',
    stirFrying: 'Stirfry',
    sautéing: 'Sautering',
    panFrying: 'Panfrying',
    baking_1: 'Baking',
    roasting_2: 'Risting',
    broiling: 'Broiling',
    grilling_2: 'Grilling',
    toasting_1: 'Risting',
    warming: 'Oppvarming',
    heating: 'Oppvarming',
    cooking_1: 'Matlaging',
    preparing_1: 'Forberedelse',
    making: 'Gjøring',
    creating: 'Skaping',
    producing: 'Produksjon',
    manufacturing: 'Produksjon',
    fabricating: 'Fabricasjon',
    assembling: 'Samling',
    constructing: 'Konstruksjon',
    building: 'Bygging',
    erecting: 'Reising',
    raising_1: 'Reising',
    lifting_1: 'Løft',
    lowering: 'Senking',
    dropping: 'Slipp',
    falling: 'Fallende',
    descending: 'Nedstigende',
    dropping_1: 'Nedfall',
    plunging: 'Plunging',
    diving_1: 'Dykkende',
    submerging: 'Undermerkning',
    immersing: 'Immersion',
    dipping: 'Dipping',
    soaking: 'Innblanding',
    wetting: 'Vetting',
    moistening: 'Fukting',
    humidifying: 'Fukting',
    watering: 'Vanning',
    irrigating: 'Vanning',
    flooding: 'Oversvømmelse',
    drenching: 'Våting',
    soaking_1: 'Innblanding',
    steeping: 'Steeping',
    infusing: 'Innføring',
    extracting: 'Ekstrahering',
    removing: 'Fjerning',
    extracting_1: 'Ekstrahering',
    pulling: 'Trekk',
    dragging: 'Dra',
    towing: 'Towing',
    hauling: 'Hauling',
    carrying: 'Bæring',
    transporting: 'Transport',
    shipping: 'Forsendelse',
    delivering: 'Levering',
    distributing: 'Distribusjon',
    allocating: 'Tildeling',
    assigning: 'Tildeling',
    appointing: 'Utnævnelse',
    designating: 'Påpekende',
    nominating: 'Nomination',
    selecting: 'Seleksjon',
    choosing: 'Valg',
    picking: 'Plukking',
    choosing_1: 'Valg',
    deciding: 'Avgjørelse',
    determining: 'Avgjørelse',
    resolving: 'Oppløsning',
    settling: 'Settling',
    concluding_2: 'Konklusjon',
    finishing_2: 'Fullførelse',
    completing_2: 'Fullførelse',
    accomplishing_1: 'Accomplishment',
    achieving_1: 'Achievement',
    attaining: 'Attainment',
    reaching: 'Nåing',
    gaining: 'Oppnåing',
    earning: 'Opptjening',
    winning_1: 'Seiring',
    succeeding_2: 'Suksess',
    thriving_2: 'Trivsel',
    flourishing_2: 'Flourishing',
    prospering_2: 'Prosperity',
    blooming_1: 'Blomstring',
    blossoming: 'Blomstring',
    flowering_1: 'Blomstring',
    growing_2: 'Vekst',
    expanding: 'Utvidelse',
    extending: 'Utover',
    stretching: 'Strekk',
    spreading: 'Spreiding',
    scattering: 'Spredning',
    dispersing: 'Spredning',
    dispersing_1: 'Spredning',
    dissipating: 'Dissipation',
    evaporating: 'Fordampning',
    vanishing: 'Forsvinning',
    disappearing: 'Forsvinning',
    fading: 'Visning',
    waning: 'Avtagende',
    declining: 'Nedgang',
    decreasing: 'Reduksjon',
    diminishing: 'Reduksjon',
    reducing: 'Reduksjon',
    minimizing: 'Minimer',
    lowering_1: 'Senking',
    dropping_2: 'Nedsettelse',
    falling_1: 'Fall',
    sinking_1: 'Synking',
    subsiding: 'Nedsettelse',
    settling_1: 'Settling',
    calming: 'Beroliging',
    soothing: 'Beroliging',
    pacifying: 'Pacification',
    appeasing: 'Apaisement',
    quieting: 'Quietning',
    silencing: 'Stillhet',
    muting: 'Muting',
    damping: 'Demping',
    suppressing: 'Undertrykkelse',
    repressing: 'Undertrykkelse',
    inhibiting: 'Inhibering',
    restraining: 'Restraint',
    confining: 'Avgrensning',
    limiting: 'Begrensning',
    restricting: 'Begrensning',
    constraining: 'Tvingende',
    forcing: 'Tving',
    compelling: 'Compelling',
    obliging: 'Pliktig',
    requiring: 'Krav',
    demanding: 'Krevende',
    expecting: 'Forventning',
    anticipating: 'Anticipasjon',
    predicting: 'Prediksjon',
    forecasting: 'Prognosis',
    prophesying: 'Profeti',
    divining: 'Spådom',
    guessing: 'Gjetning',
    surmising: 'Gjetning',
    conjecturing: 'Konjektur',
    speculating: 'Spekulering',
    theorizing: 'Teorisering',
    hypothesizing: 'Hypotesering',
    assuming: 'Forutsetning',
    supposing: 'Forutsetning',
    presuming: 'Forutsetning',
    believing: 'Tro',
    thinking_1: 'Tenkning',
    considering: 'Overveielse',
    contemplating: 'Kontemplasjon',
    pondering: 'Pondering',
    musing: 'Musing',
    reflecting: 'Refleksjon',
    meditating: 'Meditasjon',
    concentrating: 'Konentrasjon',
    focusing: 'Fokus',
    focusing_1: 'Fokus',
    focusing_2: 'Fokus',
    focusing_3: 'Fokus',
  },

  /* ── Helper Text (30+) ── */
  helper: {
    email_1: 'Bruk din e-postadresse for å logge inn',
    password_1: 'Bruk minst 8 tegn med bokstaver og tall',
    username_1: 'Velg et unikt brukernavn',
    name_1: 'Skriv inn ditt fulle navn',
    phone_1: 'Bruk formatet +47 123 45 678',
    bio_1: 'Fortell litt om deg selv (maks 500 tegn)',
    location_1: 'Hvor bor du?',
    birthday_1: 'Når har du bursdag?',
    category_1: 'Velg en kategori',
    tag_2: 'Legg til nøkkelord',
    search_1: 'Skriv for å søke...',
    filter_1: 'Filtrer resultater med disse alternativene',
    sort_1: 'Velg hvordan du vil sortere',
    upload_1: 'Dra og slipp filer her',
    download_2: 'Filene vil bli lastet ned',
    delete_2: 'Denne handlingen kan ikke angres',
    edit_3: 'Endre informasjonen din',
    save_2: 'Informasjonen din vil bli lagret',
    cancel_1: 'Endringene dine vil ikke bli lagret',
    confirm_1: 'Er du sikker på at du vil fortsette?',
    accept_1: 'Du aksepterer vilkårene',
    decline_1: 'Du kan alltid akseptere senere',
    retry_1: 'Prøv igjen om noen sekunder',
    refresh_2: 'Oppdater siden for ny informasjon',
    loading_2: 'Dette tar kun et øyeblikk',
    success_1: 'Bra jobbet!',
    error_1: 'Noe gikk galt. Vennligst prøv igjen.',
    warning_1: 'Vær oppmerksom',
    info_2: 'Her er litt informasjon',
    help_2: 'Vi er her for å hjelpe',
    tips_1: 'Her er noen tips',
    guide_1: 'Følg denne guiden',
    support_1: 'Kontakt oss for hjelp',
    feedback_2: 'Vi setter pris på din tilbakemelding',
    report_1: 'Rapporter eventuelle problemer',
    contact_1: 'Vi svarer vanligvis innen 24 timer',
    about_1: 'Lær mer om oss',
    privacy_1: 'Din personvern er viktig for oss',
    terms_1: 'Les våre vilkår nøye',
    version_2: 'Du bruker den nyeste versjonen',
    update_3: 'En oppdatering er tilgjengelig',
    install_1: 'Installer for beste opplevelse',
    launch_1: 'Appen vil starte snart',
    minimize_2: 'Appen vil fortsette i bakgrunnen',
    maximize_2: 'Appen vil fylle skjermen',
    restore_2: 'Appen vil回到 normal størrelse',
    zoomIn_2: 'Du kan zoome opp til 10x',
    zoomOut_2: 'Du kan zoome ut til 0.1x',
    fit_1: 'Innholdet vil tilpasse skjermen',
    reset_1: 'Alle innstillinger vil回到 standard',
    default_1: 'Dette er standardinnstillingen',
    custom_1: 'Du kan tilpasse dette etter behov',
    auto_1: 'Systemet vil velge automatisk',
    manual_1: 'Du må velge manuelt',
    smart_1: 'AI vil hjelpe deg med valg',
    simple_1: 'Dette er den enkleste måten',
    advanced_1: 'Avanserte alternativer er tilgjengelige',
    basic_1: 'Grønne alternativer er tilgjengelige',
    pro_1: 'Profesjonelle funksjoner er tilgjengelige',
    lite_1: 'Lettversjon for lavere ytelse',
    full_3: 'Fullversjon med alle funksjoner',
    mini_1: 'Kompakt visning',
    large_1: 'Stor visning for bedre lese',
    extraLarge_1: 'Ekstra stor visning',
    tiny_1: 'Meget liten visning',
    medium_1: 'Middels visning',
    small_1: 'Liten visning',
    big_1: 'Stor visning',
    huge_1: 'Ekstra stor visning',
    giant_1: 'Kjempestor visning',
    massive_1: 'Massiv visning',
  },

  /* ── Onboarding Prompts (30+) ── */
  onboarding: {
    welcome_1: 'Velkommen til Tosom',
    welcomeSubtitle: 'To mennesker. Én reise.',
    letBegin: 'La oss begynne reisen din',
    whatName: 'Hva heter du?',
    whatNameHelp: 'Skriv inn ditt fulle navn',
    whatAge: 'Hvor gammel er du?',
    whatAgeHelp: 'Vi bruker dette for å tilpasse opplevelsen',
    whatGender: 'Hva er ditt kjønn?',
    whatGenderHelp: 'Dette er valgfritt',
    whatLookingFor: 'Hva leter du etter?',
    whatLookingForHelp: 'Vi hjelper deg med å finne det',
    personalityQ1: 'Hvordan beskriver du deg selv?',
    personalityQ1Options: ['Roelig', 'Eventyrlysten', 'Tankefull', 'Passjonert'],
    personalityQ2: 'Hva er viktigst for deg?',
    personalityQ2Options: ['Dybde', 'Autenticitet', 'Vekst', 'Tilknytning'],
    personalityQ3: 'Hvordan liker du å tilbringe tid?',
    personalityQ3Options: ['Dype samtaler', 'Kreative prosjekter', 'Natur', 'Kultur'],
    interestsTitle: 'Hva er du interessert i?',
    interestsSubtitle: 'Velg minst 3 interesser',
    interestsHelp: 'Dette hjelper oss med å finne resonans',
    relationshipGoalsTitle: 'Hva er dine relasjonsmål?',
    relationshipGoalsSubtitle: 'Velg det som passer deg best',
    relationshipGoalsHelp: 'Disse målene vil guide reisen din',
    aiPersonalizationTitle: 'La AI hjelpe deg',
    aiPersonalizationSubtitle: 'Vår AI lærer om deg over tid',
    aiPersonalizationHelp: 'Hvori vil du ha AI-assistanse?',
    aiOptions: ['Meldingsforslag', 'Reiseveiledning', 'Innsikter', 'Isbryter'],
    readyToBegin: 'Er du klar til å starte?',
    readyToBeginSubtitle: 'Din personlige reise venter',
    finishSetup: 'Fullfør oppsettet',
    skipTour: 'Hopp over og se guiden senere',
    seeDemo: 'Se en demo først',
    needHelp: 'Trenger du hjelp?',
    contactUs: 'Kontakt oss på support@tosom.no',
    readMore: 'Les mer på vår nettside',
    privacyNote: 'Vi behandler dine data med omtanke',
    privacyLink: 'Les personvernserklæringen',
    termsNote: 'Ved å fortsette godkjenner du våre vilkår',
    termsLink: 'Les vilkårene',
    dataCollection: 'Vi samler kun nødvendig data',
    dataUsage: 'For å tilpasse opplevelsen din',
    dataSharing: 'Vi deler aldri dine data med tredjeparter',
    dataStorage: 'Dataene dine lagres sikkert',
    dataDeletion: 'Du kan slette alle data når som helst',
    accountCreated: 'Kontoen din er opprettet!',
    profileComplete: 'Profilen din er komplett',
    firstMatch: 'Din første match er klar',
    firstJourney: 'Din første reise venter',
    firstMessage: 'Du har ingen meldinger ennå',
    firstMemory: 'Lag din første minne',
    firstMilestone: 'Nå til din første milestone',
    firstGoal: 'Sett ditt første mål',
    firstCalendar: 'Legg til en hendelse i kalenderen',
    firstJournal: 'Begynn å skrive i dagboken',
  },

  /* ── AI Prompts (30+) ── */
  ai: {
    greeting_2: 'Hei! Jeg er Tosom AI-assistent.',
    greetingSub: 'Kan jeg hjelpe deg med noe?',
    whatNeed: 'Hva kan jeg hjelpe deg med?',
    suggestMe: 'Jeg kan hjelpe med:',
    suggestMeList: ['Meldingsforslag', 'Reiseveiledning', 'Innsikter', 'Spørsmål'],
    writeMessage: 'Skriv en melding til din partner',
    writeMessageSub: 'Jeg kan foreslå meldinger',
    improveWriting: 'Forbedre din skrivemåte',
    improveWritingSub: 'Jeg kan hjelpe med tonen og strukturen',
    suggestQuestions: 'Foreslå spørsmål',
    suggestQuestionsSub: 'Jeg kan finne meningsfulle spørsmål',
    giveInsights: 'Gi innsikter',
    giveInsightsSub: 'Jeg kan analysere mønstre i deres interaksjon',
    guideJourney: 'Veilede reisen',
    guideJourneySub: 'Jeg kan foreslå neste steg i deres reiseforløp',
    icebreakers: 'Trenger du isbrytere?',
    icebreakersSub: 'Jeg har mange gode spørsmål',
    journeyTip: 'Reisetips',
    journeyTipSub: 'Her er noe forslag for deres neste reise',
    milestoneApproach: 'Nærmer deg et milestone!',
    milestoneApproachSub: 'Er du klar for dette spesielle øyeblikket?',
    memorySuggestion: 'Minne forslag',
    memorySuggestionSub: 'Her er noe forslag for deres neste minne',
    resonanceCheck: 'Resonans sjekk',
    resonanceCheckSub: 'Dere har god resonans! Her er hvorfor...',
    moodCheck: 'Stemningssjekk',
    moodCheckSub: 'Hvordan føler du deg i dag?',
    encouragement: 'Oppmuntring',
    encouragementSub: 'Dere gjør det bra! Fortsett slik...',
    relationshipAdvice: 'Relasjonsråd',
    relationshipAdviceSub: 'Her er noe visdom for dere',
    communicationTip: 'Kommunikasjonstips',
    communicationTipSub: 'Her er hvordan du kan kommunisere bedre',
    dateIdea: 'Date idé',
    dateIdeaSub: 'Her er noen date idéer for dere',
    giftSuggestion: 'Gave forslag',
    giftSuggestionSub: 'Her er noen gave idéer',
    anniversaryReminder: 'Årsdags påminner',
    anniversaryReminderSub: 'En spesiell dag er snart!',
    notification: 'Melding',
    notificationSub: 'Du har en ny melding fra Tosom AI',
    newFeature: 'Ny funksjon',
    newFeatureSub: 'Vi har lagt til noe nytt for deg',
    updateAvailable: 'Oppdatering tilgjengelig',
    updateAvailableSub: 'Tosom har blitt bedre!',
    maintenance: 'Vedlikehold',
    maintenanceSub: 'Vi utfører vedlikehold snart',
    scheduled: 'Planlagt',
    scheduledSub: 'Dette er planlagt vedlikehold',
    maintenanceComplete: 'Vedlikehold ferdig',
    maintenanceCompleteSub: 'Vi er ferdig med vedlikeholdet',
    comingSoon: 'Kommer snart',
    comingSoonSub: 'Vi jobber med noe spennende',
    betaAccess: 'Beta tilgang',
    betaAccessSub: 'Bli med og test nye funksjoner',
    feedbackRequested: 'Tilbakemelding ønsket',
    feedbackRequestedSub: 'Vi vil gjerne høre hva du tenker',
    survey: 'Undersøkelse',
    surveySub: 'Ta med på en kort undersøkelse',
    vote: 'Stem',
    voteSub: 'Din stemme teller',
    poll: 'Meningsmåling',
    pollSub: 'Delta i en meningsmåling',
    contest: 'Konkurranse',
    contestSub: 'Delta i en konkurranse',
    giveaway: 'Giveaway',
    giveawaySub: 'Vinne noe fint!',
    reward: 'Belønning',
    rewardSub: 'Du har fått en belønning!',
    achievement: 'Prestasjon',
    achievementSub: 'Du har oppnådd noe!',
    milestone: 'Milestone',
    milestoneSub: 'Tillykke med milestone!',
    levelUp: 'Nivå opp',
    levelUpSub: 'Du har nådd nytt nivå!',
    promotion: 'Promosjon',
    promotionSub: 'Du har blitt oppgradert!',
    upgradeAvailable: 'Oppgradering tilgjengelig',
    upgradeAvailableSub: 'Oppgrader for mer funksjonalitet',
    premiumFeature: 'Premium funksjon',
    premiumFeatureSub: 'Dette er en premium funksjon',
    freeTrial: 'Gratis prøveperiode',
    freeTrialSub: 'Prøv gratis i 14 dager',
    subscription: 'Abonnement',
    subscriptionSub: 'Ditt abonnement fornyes snart',
    paymentFailed: 'Betaling mislyktes',
    paymentFailedSub: 'Vennligst oppdater betalingsinformasjon',
    paymentSuccess: 'Betaling vellykket',
    paymentSuccessSub: 'Takk for kjøpet!',
    orderConfirmed: 'Bestilling bekreftet',
    orderConfirmedSub: 'Din bestilling er underveis',
    orderShipped: 'Bestilling sendt',
    orderShippedSub: 'Sporing tilgjengelig',
    deliveryUpdate: 'Leveringsoppdatering',
    deliveryUpdateSub: 'Din levering er underveis',
    deliveryComplete: 'Levering fullført',
    deliveryCompleteSub: 'Takk for at du valgte Tosom',
    packageReceived: 'Pakke mottatt',
    packageReceivedSub: 'Har du mottatt pakken din?',
    packageDamaged: 'Pakke skadet',
    packageDamagedSub: 'Kontakt oss hvis pakken var skadet',
    returnRequested: 'Retur forespurt',
    returnRequestedSub: 'Vi behandler din retur',
    refundProcessed: 'Refusjon behandlet',
    refundProcessedSub: 'Tilbakebetalingen er underveis',
    warrantyClaim: 'Garantikrav',
    warrantyClaimSub: 'Vi hjelper deg med garantien',
    supportTicket: 'Støttesak',
    supportTicketSub: 'Vi svarer snart på din henvendelse',
    supportResolved: 'Støtte løst',
    supportResolvedSub: 'Er saken løst for deg?',
    supportClosed: 'Sak lukket',
    supportClosedSub: 'Saken er lukket. Takk for at du kontaktet oss.',
    chatTranscript: 'Chattlogg',
    chatTranscriptSub: 'Her er din chattlogg',
    exportChat: 'Eksporter chatt',
    exportChatSub: 'Last ned chat historikken din',
    importChat: 'Importer chatt',
    importChatSub: 'Last opp chat data',
    backupChat: 'Sikkerhetskopier chatt',
    backupChatSub: 'Sikkerhetskopier alle meldinger',
    restoreChat: 'Gjenopprett chatt',
    restoreChatSub: 'Gjenopprett fra sikkerhetskopi',
    deleteChat: 'Slett chatt',
    deleteChatSub: 'Denne handlingen kan ikke angres',
    clearChat: 'Tøm chatt',
    clearChatSub: 'Alle meldinger vil bli fjernet',
    archiveChat: 'Arkiver chatt',
    archiveChatSub: 'Chatten vil bli arkivert',
    unarchiveChat: 'Frakkiwer chatt',
    unarchiveChatSub: 'Chatten er tilbake',
    pinChat: 'Fest chatt',
    pinChatSub: 'Chatten vil være øverst',
    unpinChat: 'Frifest chatt',
    unpinChatSub: 'Chatten er frigjort',
    muteChat: 'Dempe chatt',
    muteChatSub: 'Du vil ikke motta meldinger',
    unmuteChat: 'Dempe chatt',
    unmuteChatSub: 'Du vil motta meldinger igjen',
    favoriteChat: 'Merk som favoritt',
    favoriteChatSub: 'Chatten er en favoritt',
    unfavoriteChat: 'Fjern favoritt',
    unfavoriteChatSub: 'Chatten er ikke lenger en favoritt',
    blockUser: 'Blokker bruker',
    blockUserSub: 'Du vil ikke kunne kommunisere',
    unblockUser: 'Frigjør bruker',
    unblockUserSub: 'Brukeren er frigjort',
    reportUser: 'Rapporter bruker',
    reportUserSub: 'Vi vil undersøke saken',
    muteUser: 'Dempe bruker',
    muteUserSub: 'Brukerens meldinger vil bli skjult',
    unmuteUser: 'Opphev demping av bruker',
    unmuteUserSub: 'Brukerens meldinger vil syns igjen',
    ignoreUser: 'Ignorer bruker',
    ignoreUserSub: 'Meldinger vil bli ignorerte',
    acknowledgeUser: 'Anerkjende bruker',
    acknowledgeUserSub: 'Meldinger er anerkjendte',
    respondToUser: 'Svar på bruker',
    respondToUserSub: 'Skriv et svar',
    forwardMessage: 'Videresend melding',
    forwardMessageSub: 'Velg mottager',
    replyToMessage: 'Svar på melding',
    replyToMessageSub: 'Ditt svar vil vises under',
    quoteMessage: 'Siter melding',
    quoteMessageSub: 'Siter deler av meldingen',
    editMessage: 'Rediger melding',
    editMessageSub: 'Du kan redigere denne meldingen',
    deleteMessage: 'Slett melding',
    deleteMessageSub: 'Meldingen vil bli fjernet',
    pinMessage: 'Fest melding',
    pinMessageSub: 'Meldingen vil være øverst i chatten',
    unpinMessage: 'Frifest melding',
    unpinMessageSub: 'Meldingen er ikke lenger fest',
    starMessage: 'Merk med stjerne',
    starMessageSub: 'Meldingen er merkt med stjerne',
    unstarMessage: 'Fjern stjerne',
    unstarMessageSub: 'Meldingen er ikke lenger merkt',
    highlightMessage: 'Fremheve melding',
    highlightMessageSub: 'Meldingen er fremhevet',
    unhighlightMessage: 'Fjern fremheving',
    unhighlightMessageSub: 'Meldingen er ikke lenger fremhevet',
    translateMessage: 'Oversett melding',
    translateMessageSub: 'Velg målsspråk',
    readMessage: 'Les melding',
    readMessageSub: 'Meldingen er lest',
    unreadMessage: 'Ulest melding',
    unreadMessageSub: 'Du har en ulest melding',
    messageReceived: 'Melding mottatt',
    messageReceivedSub: 'Du har mottatt en ny melding',
    messageSent: 'Melding sendt',
    messageSentSub: 'Meldingen er sendt',
    messageDelivered: 'Melding levert',
    messageDeliveredSub: 'Meldingen er levert',
    messageFailed: 'Melding mislyktes',
    messageFailedSub: 'Meldingen kunne ikke sendes',
    messagePending: 'Melding venter',
    messagePendingSub: 'Meldingen venter på leveranse',
    messageDraft: 'Melding utkast',
    messageDraftSub: 'Du har et utkast som venter',
    messageScheduled: 'Melding planlagt',
    messageScheduledSub: 'Meldingen vil bli sendt senere',
    messageCancel: 'Avbryt melding',
    messageCancelSub: 'Meldingen vil ikke bli sendt',
    messageResend: 'Send melding igjen',
    messageResendSub: 'Meldingen vil bli sendt på nytt',
    messageRetry: 'Prøv igjen',
    messageRetrySub: 'Meldingen vil bli sendt igjen',
    messageRetryFailed: 'Prøving mislyktes',
    messageRetryFailedSub: 'Meldingen kunne ikke sendes',
    messageExpired: 'Melding utløpt',
    messageExpiredSub: 'Meldingen er utløpt',
    messageDeleted: 'Melding slettet',
    messageDeletedSub: 'Meldingen er slettet',
    messageRestored: 'Melding gjenopprettet',
    messageRestoredSub: 'Meldingen er gjenopprettet',
    messageArchived: 'Melding arkivert',
    messageArchivedSub: 'Meldingen er arkivert',
    messageUnarchived: 'Melding fra arkiv',
    messageUnarchivedSub: 'Meldingen er tilbake',
    messagePinned: 'Melding festet',
    messagePinnedSub: 'Meldingen er festet',
    messageUnpinned: 'Melding frigjort',
    messageUnpinnedSub: 'Meldingen er frigjort',
    messageStarred: 'Melding merkt',
    messageStarredSub: 'Meldingen er merkt med stjerne',
    messageUnstarred: 'Melding framerkt',
    messageUnstarredSub: 'Meldingen er ikke lenger merkt',
    messageHighlighted: 'Melding fremhevet',
    messageHighlightedSub: 'Meldingen er fremhevet',
    messageUnhighlighted: 'Melding ikke fremhevet',
    messageUnhighlightedSub: 'Meldingen er ikke lenger fremhevet',
    messageTranslated: 'Melding oversatt',
    messageTranslatedSub: 'Meldingen er oversatt',
    messageRead: 'Melding lest',
    messageReadSub: 'Meldingen er lest',
    messageUnread: 'Melding ulest',
    messageUnreadSub: 'Meldingen er ulest',
  },
} as const;

export default microcopy;