$ErrorActionPreference = 'Stop'
$ts = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
$profile = [Environment]::GetFolderPath('UserProfile')
$base = Join-Path $profile 'AIWorkspace'
$scripts = Join-Path $base 'scripts'
New-Item -ItemType Directory -Force -Path $base | Out-Null
New-Item -ItemType Directory -Force -Path $scripts | Out-Null
try { Copy-Item $MyInvocation.MyCommand.Path -Destination (Join-Path $scripts 'inventory.ps1') -Force -ErrorAction Stop } catch {}

$cs   = Get-CimInstance Win32_ComputerSystem
$os   = Get-CimInstance Win32_OperatingSystem
$cpu  = @(Get-CimInstance Win32_Processor)
$phys = @(Get-CimInstance Win32_PhysicalMemory)
$disks = @(Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3')
$totalRamGB = [math]::Round($cs.TotalPhysicalMemory/1GB, 2)
$uptime = (New-TimeSpan -Start $os.LastBootUpTime -End (Get-Date)).ToString()

$regPaths = @(
  'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*',
  'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*',
  'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*'
)
$apps = Get-ItemProperty $regPaths -ErrorAction SilentlyContinue |
  Where-Object { $_.DisplayName } |
  Select-Object DisplayName, DisplayVersion, Publisher, InstallDate |
  Sort-Object DisplayName -Unique

$driveRows = $disks | ForEach-Object {
  [PSCustomObject]@{
    Drive  = $_.DeviceID
    Volume = $_.VolumeName
    SizeGB = [math]::Round($_.Size/1GB,1)
    FreeGB = [math]::Round($_.FreeSpace/1GB,1)
  }
}
$topC = Get-ChildItem 'C:\' -Force -ErrorAction SilentlyContinue | Select-Object Name, @{N='IsFolder';E={$_.PSIsContainer}}
$topProfile = Get-ChildItem $profile -Force -ErrorAction SilentlyContinue | Select-Object Name, @{N='IsFolder';E={$_.PSIsContainer}}

# ---------- system-overview.md ----------
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# System Overview - ' + $cs.Name)
[void]$sb.AppendLine('')
[void]$sb.AppendLine('_Generated by AI agent on ' + $ts + '_')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Computer')
[void]$sb.AppendLine('| Property | Value |')
[void]$sb.AppendLine('|---|---|')
[void]$sb.AppendLine('| Name | ' + $cs.Name + ' |')
[void]$sb.AppendLine('| Manufacturer | ' + $cs.Manufacturer + ' |')
[void]$sb.AppendLine('| Model | ' + $cs.Model + ' |')
[void]$sb.AppendLine('| System type | ' + $cs.SystemType + ' |')
[void]$sb.AppendLine('| Workgroup/Domain | ' + $cs.Domain + ' |')
[void]$sb.AppendLine('| Total physical memory | ' + $totalRamGB + ' GB (' + $phys.Count + ' module(s)) |')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Operating System')
[void]$sb.AppendLine('| Property | Value |')
[void]$sb.AppendLine('|---|---|')
[void]$sb.AppendLine('| Name | ' + $os.Caption + ' |')
[void]$sb.AppendLine('| Version | ' + $os.Version + ' |')
[void]$sb.AppendLine('| Build | ' + $os.BuildNumber + ' |')
[void]$sb.AppendLine('| Install date | ' + $os.InstallDate + ' |')
[void]$sb.AppendLine('| Last boot | ' + $os.LastBootUpTime + ' |')
[void]$sb.AppendLine('| Uptime | ' + $uptime + ' |')
[void]$sb.AppendLine('| System directory | ' + $os.SystemDirectory + ' |')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## CPU')
foreach ($c in $cpu) {
  [void]$sb.AppendLine('')
  [void]$sb.AppendLine('- **' + $c.Name + '**')
  [void]$sb.AppendLine('  - Cores: ' + $c.NumberOfCores + ' | Logical processors: ' + $c.NumberOfLogicalProcessors)
  [void]$sb.AppendLine('  - Max speed: ' + $c.MaxClockSpeed + ' MHz')
}
[void]$sb.AppendLine('')
[void]$sb.AppendLine('_Workspace: ' + $base + '_')
Set-Content -Path (Join-Path $base 'system-overview.md') -Value $sb.ToString() -Encoding UTF8

# ---------- applications.md ----------
$ab = New-Object System.Text.StringBuilder
[void]$ab.AppendLine('# Installed Applications - ' + $cs.Name)
[void]$ab.AppendLine('')
[void]$ab.AppendLine('_Generated ' + $ts + '. Total entries: ' + $apps.Count + '_')
[void]$ab.AppendLine('')
[void]$ab.AppendLine('| Name | Version | Publisher | Installed |')
[void]$ab.AppendLine('|---|---|---|---|')
foreach ($a in $apps) {
  $n = [string]$a.DisplayName -replace '\|','/'
  $p = [string]$a.Publisher -replace '\|','/'
  [void]$ab.AppendLine('| ' + $n + ' | ' + $a.DisplayVersion + ' | ' + $p + ' | ' + $a.InstallDate + ' |')
}
Set-Content -Path (Join-Path $base 'applications.md') -Value $ab.ToString() -Encoding UTF8

# ---------- folders.md ----------
$fb = New-Object System.Text.StringBuilder
[void]$fb.AppendLine('# Storage and Folder Overview - ' + $cs.Name)
[void]$fb.AppendLine('')
[void]$fb.AppendLine('_Generated ' + $ts + '_')
[void]$fb.AppendLine('')
[void]$fb.AppendLine('## Drives')
[void]$fb.AppendLine('| Drive | Volume | Size (GB) | Free (GB) |')
[void]$fb.AppendLine('|---|---|---|---|')
foreach ($d in $driveRows) {
  [void]$fb.AppendLine('| ' + $d.Drive + ' | ' + $d.Volume + ' | ' + $d.SizeGB + ' | ' + $d.FreeGB + ' |')
}
[void]$fb.AppendLine('')
[void]$fb.AppendLine('## C:\ (top level)')
foreach ($i in $topC) {
  $t = if ($i.IsFolder) { 'folder' } else { 'file' }
  [void]$fb.AppendLine('- ' + $i.Name + ' (' + $t + ')')
}
[void]$fb.AppendLine('')
[void]$fb.AppendLine('## User profile: ' + $profile)
foreach ($i in $topProfile) {
  $t = if ($i.IsFolder) { 'folder' } else { 'file' }
  [void]$fb.AppendLine('- ' + $i.Name + ' (' + $t + ')')
}
Set-Content -Path (Join-Path $base 'folders.md') -Value $fb.ToString() -Encoding UTF8

# ---------- LOG.md ----------
$logPath = Join-Path $base 'LOG.md'
if (-not (Test-Path $logPath)) {
  $lb = New-Object System.Text.StringBuilder
  [void]$lb.AppendLine('# Agent Work Log - ' + $cs.Name)
  [void]$lb.AppendLine('')
  [void]$lb.AppendLine('_Running record of what we do in this workspace._')
  [void]$lb.AppendLine('')
  Set-Content -Path $logPath -Value $lb.ToString() -Encoding UTF8
}
Add-Content -Path $logPath -Value ('## ' + $ts)
Add-Content -Path $logPath -Value '- Created AIWorkspace and generated initial inventory: system-overview.md, applications.md, folders.md.'

Write-Output 'WORKSPACE=' + $base
Write-Output 'SYSTEM=' + $cs.Name
Write-Output 'OS=' + $os.Caption + ' ' + $os.Version
Write-Output 'RAM_GB=' + $totalRamGB
Write-Output 'APP_COUNT=' + $apps.Count
Write-Output 'DRIVE_COUNT=' + $driveRows.Count
Write-Output 'STATUS=OK'
